### PR TITLE
Backports/3.8 14.3

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary
Backports: 
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1693
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1662
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1677
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1669
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1691
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1665
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1698
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1708
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1716

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by michalvavrik — APPROVED** [review]
I don't see the IDE config backported, so probably the PR description would deserve update. Changes LGTM, thx!

**Comment by fedinskiy** [comment]
IDE config was updated earlier: https://github.com/quarkus-qe/quarkus-test-suite/commit/7e42b88d5b04538cbb1ef5286450c5b34f859e90

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
Failure in `OpenShiftQpidIT` on openshift native seems like a flaky tests (and it in the module, which was not changed)

**Pull request merged**
