### PR TITLE
[3.2] Re-run failing tests to limit flakiness

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1633.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by rsvoboda** [comment]
I know this is backport, but why different numbers of re-runs (1 vs. 2) and wouldn't be parametrization of this through a property more handy?

**Comment by michalvavrik** [comment]
> I know this is backport, 

np, I'm open to changes in main or in backport (and port them)

> but why different numbers of re-runs (1 vs. 2)

- Re-run of JVM is not a big deal as it only starts app again, no JAR build etc. (and starting containers etc.)
- Re-run in native is even lesser deal on main when this change https://github.com/quarkus-qe/quarkus-test-framework/pull/1021 is propagated to TS, because native executable starts even quicker, so re-run is cheap (it is not true for 3.2 for there build works differently and it will not be re-used, but still, it should be rather stable without failures, right?)
- Re-run of OpenShift requires creating new project, pushing it to the OpenShift + same as above, I think such a re-run will take significantly longer depending on the scenario.

However @mjurc had same doubts, I'm not sure, if you feel it doesn't matter, we can also re-run it twice in OpenShift. I was afraid of these serial failures when there is bump of Fabric8 and many tests are not working, it would take longer.

> and wouldn't be parametrization of this through a property more handy?

I'd expect you can easily overrun this with `-Dfailsafe.rerunFailingTestsCount=3` if you need to. Didn't try it, but command line should have higher priority, right? In which case I don't see an advantage.

**Comment by michalvavrik** [comment]
FYI https://maven.apache.org/surefire/maven-failsafe-plugin/examples/rerun-failing-tests.html#rerun-failing-tests

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
