### PR TITLE
[3.15] Backports

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary
Backports these PRs:

- https://github.com/quarkus-qe/quarkus-test-suite/pull/2059
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2060
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2066
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2073
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2075
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2077
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2080

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
@michalvavrik it is backport of your commit (https://github.com/quarkus-qe/quarkus-test-suite/pull/2060) Any idea, why server.jks may be not generated/found?

**Comment by michalvavrik** [comment]
> @michalvavrik it is backport of your commit (#2060) Any idea, why server.jks may be not generated/found?

probably backports are not one to one, let me have a look

**Comment by fedinskiy** [comment]
@michalvavrik I backported the merge commit (neither `2046096aefd3679d43e241391e9cd0791362966` nor `46b1641d121a565fe365cf5f08b9f590f356a39a` are in our main trunk)

**Comment by michalvavrik** [comment]
> @michalvavrik I backported the merge commit (neither `2046096aefd3679d43e241391e9cd0791362966` nor `46b1641d121a565fe365cf5f08b9f590f356a39a` are in our main trunk)

in that case commit title is wrong. in any case, this only happens when commits doesn't apply, I'll report back

**Comment by michalvavrik** [comment]
I still see a difference between these commits. In the main branch PR https://github.com/quarkus-qe/quarkus-test-suite/pull/2060/files I can see `kafkaSSL/src/main/java` that are completely missing in this PR. Without these changes it cannot work properly.

**Comment by michalvavrik** [comment]
sure, thanks

**Pull request merged**
