### PR TITLE
RemoteDev scenario to check DEV ui is not found

### PR DESCRIPTION
**Pull request by Sgitario**
This PR is to verify https://issues.redhat.com/browse/QUARKUS-834

### CODE REVIEW

**Review by rsvoboda — COMMENTED** [review]
`http/http-minimum` is getting packed, I think we should put this into `http/http-advanced` and trim `http/http-minimum`in another PR a bit (e.g. move live coding test to advanced).

**Comment by Sgitario** [comment]
> `http/http-minimum` is getting packed, I think we should put this into `http/http-advanced` and trim `http/http-minimum`in another PR a bit (e.g. move live coding test to advanced).

Moved

**Review by rsvoboda — APPROVED** [review]

**Comment by rsvoboda** [comment]
Waiting for CI

**Comment by Sgitario** [comment]
The failure is caused by a change in upstream related to CLI that will be addressed in https://github.com/quarkus-qe/quarkus-test-suite/pull/251.
Merging.

**Pull request merged**
