### PR TITLE
[3.8] Disable OpenShiftTodoDemoIT in IBM PE/Z Maven profile as webbundler does not have supported for s390x & ppc64le.

### PR DESCRIPTION
**Pull request by ashwinik30**
### Summary

webbundler does not have supported for s390x & ppc64le. OpenShiftTodoDemoIT for p/z

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
Also you will need to port this to the main branch.

**Comment by ashwinik30** [comment]
@michalvavrik will create PR for main in sometime

**Comment by jedla97** [comment]
Just FYI the todoapp for latest Quarkus don't use web-bundler but [web-dependency-locator](https://github.com/quarkusio/todo-demo-app/blob/main/pom.xml#L83) so it's possible that in future RHBQ it will work (So maybe you can try it).

**Comment by michalvavrik** [comment]
Validate format fails as 

> Just FYI the todoapp for latest Quarkus don't use web-bundler but [web-dependency-locator](https://github.com/quarkusio/todo-demo-app/blob/main/pom.xml#L83) so it's possible that in future RHBQ it will work (So maybe you can try it).

In that case let's not port this.

**Comment by michalvavrik** [comment]
@ashwinik30 please fix formatting

**Comment by michalvavrik** [comment]
ping @ashwinik30

**Pull request closed without merging**
