### PR TITLE
[2.7] Quarkus kubernetes support for service binding

### PR DESCRIPTION
**Pull request by mjurc**
* Adding a test for Quarkus kubernetes support for service binding from
  Crunchy Postgres.

### Summary

(Summarize the problem solved by this PR, and how to verify it manually)

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [x] New scenario (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by pjgg** [comment]
same as https://github.com/quarkus-qe/quarkus-test-suite/pull/746

**Review by pjgg — CHANGES_REQUESTED** [review]
CI didn't pass

**Comment by mjurc** [comment]
run tests

**Review by pjgg — APPROVED** [review]
LGTM

**Comment by mjurc** [comment]
run tests

**Comment by pjgg** [comment]
Could you review Native errors and check if are related to this PR?

**Comment by mjurc** [comment]
@pjgg Failures not related.

Gonna have the tests re-ran, as it seems that cluster was not ready at the time...

run tests

**Pull request merged**
