### PR TITLE
[3.8] Backport for 3.8 branch 20.6.2024

### PR DESCRIPTION
**Pull request by jedla97**
### Summary

Backport of:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1834
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1838
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1839 + change from rest to resteasy-reactive

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jedla97** [comment]
run tests

**Comment by rsvoboda** [comment]
It seems https://github.com/quarkusio/quarkus-backports app wasn't used to help to prepare this backport

Symptoms:
 - `cherry-pick` command wasn't executed with `-x` ... from the help message: When recording the commit, append a line that says "(cherry picked from commit ...)" to the original commit message in order to indicate which commit this change was cherry-picked from.
 - backport label wasn't removed from the relevant PRs - see https://github.com/quarkus-qe/quarkus-test-suite/issues?q=label%3Atriage%2Fbackport-3.8+is%3Aclosed

**Comment by jedla97** [comment]
@rsvoboda Thanks I didn't know about this tool. Only problem with our repo is that we not using milestone so the 2.7 need to be used and after marking it as done in app the milestone from issue need to be removed.

**Comment by rsvoboda** [comment]
We can create 3.8 milestone, we own the repo ...

**Comment by jedla97** [comment]
run tests

**Review by gtroitsk — APPROVED** [review]
LGTM

**Pull request merged**
