### PR TITLE
[3.2] Bump Quarkus version to 3.2.11.Final

### PR DESCRIPTION
**Pull request by mocenas**
### Summary

Bump default quarkus version to 3.2.11.Final

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by mocenas** [comment]
run tests

**Review by michalvavrik — CHANGES_REQUESTED** [review]
You also need to bump the workflow Quarkus CLI version.

**Comment by mocenas** [comment]
> You also need to bump the workflow Quarkus CLI version.

done.

**Comment by mocenas** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]

**Pull request merged**
