### PR TITLE
Bump FW to  1.3.0.Beta5, migrate to Jakarta and disable javax tests

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

- Disables messaging/qpid till quarkus-qpid-jms  that uses Jakarta is released
- Also disables external application tests till external projects (QS, Workshops, Todo app) migrates to Jakarta (that's till they use Quarkus 3+)
- Javax stuff is migrated to Jakarta
- FW bumped to 1.3.0.Beta5 that also sports jakarta
- Changes in Hibernate Reactive (Panache) are forced by https://github.com/quarkusio/quarkus/pull/29761, I couldn't make it work without session and session does not support `Multi`. Also panache query method `stream` is gone
- Exclusion of commented out modules in `workflos/pr/yaml` is forced by the fact that changes (Jakarta migration) has been done in these modules, so they are detected, but not part of the project (not submodules), therefore we run into maven error. I'll get rid of that condition minutes after this PR is merged in a separate PR
- CLI stream for 999-SNAPSHOT has been fixed to 3.0 for now till Quarkus 3 final is released
- native profile for couple of modules must be disabled due to https://github.com/quarkusio/quarkus/issues/31105
- OpenShift failures comes down to changes in K8 fabric client and fix is not trivial, I'll need to refactor OpenShiftClient bit, therefore we need to ignore them for moment being
- Pact producer test has started failing on 14.2. and I can't quickly find why, there it is disabled
- Pact's `AmpqTestTarget` is deprecated for quite a while now, so I migrated it to `MesssageTestTarget` https://github.com/pact-foundation/pact-jvm/commit/3d56a8ab34d1233ae9abfcb3ef3a6c116d0a7575 (not related to failure, fails anyway)

Native run can't be verified here as there is 6 hours timeout - https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits, however I'll verify the PR locally.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
@mjurc my main issue is ATM that here native run can't be verified and locally it takes eternity, I'll try to set up some multi module test for myself to verify results; apart of native, OC runs are expected to fail

**Comment by michalvavrik** [comment]
I set up Jenkins job `mvavrik-quarkus-main-rhel8-jdk17-openshift-ts-native` for native verification.

**Review by mjurc — APPROVED** [review]
Thanks for the update.

**Comment by michalvavrik** [comment]
Approval granted, all runs are green, native is going to be cancelled, merging.

**Pull request merged**
