### PR TITLE
Add MongoDB scenario

### PR DESCRIPTION
**Pull request by jsmrcka**
Part of test development for QUARKUS-1061.

### CODE REVIEW

**Review by pjgg — CHANGES_REQUESTED** [review]
Overall looks good but I miss more scenarios as:
- cover Projections 
db.inventory.find( { name: "test_name" }, { name: 1, description: 0 } )

- a more complex Mongo Object. I mean instead of a plain object we could try a document that has a hierarchy and see how Quarkus Codec deal with that.

**Comment by jsmrcka** [comment]
> Overall looks good but I miss more scenarios as:
> 
>     * cover Projections
>       db.inventory.find( { name: "test_name" }, { name: 1, description: 0 } )
> 
>     * a more complex Mongo Object. I mean instead of a plain object we could try a document that has a hierarchy and see how Quarkus Codec deal with that.

@pjgg I pushed updates that adress all your suggestions. I have kept them in separate commits, maybe that helps with review. I will squash them before merging.

**Comment by jsmrcka** [comment]
run tests

**Comment by jsmrcka** [comment]
run tests

**Comment by jsmrcka** [comment]
run tests

**Review by pjgg — APPROVED** [review]
LGTM!

**Comment by rsvoboda** [comment]
@pjgg / @jsmrcka next time please squash the commit, 11 commits looks like too much for one PR

**Pull request merged**
