### PR TITLE
Backport/3.2

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary
Backports:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1356
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1361
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1368
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1351
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1370
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1374

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
GH Actions are not run, Jenkins runs are red

**Comment by fedinskiy** [comment]
run tests

**Comment by rsvoboda** [comment]
```
Error:  /home/runner/work/quarkus-test-suite/quarkus-test-suite/sql-db/narayana-transactions/src/main/java/io/quarkus/ts/transactions/recovery/driver/CrashingXADataSource.java:[70,17] cannot find symbol
Error:    symbol:   method dataSources()
Error:    location: class io.quarkus.datasource.runtime.DataSourcesBuildTimeConfig
```

**Comment by fedinskiy** [comment]
run tests

**Comment by rsvoboda** [comment]
@fedinskiy could you look into OCP failures?

**Comment by fedinskiy** [comment]
@rsvoboda already. Looks like resource conflict to me. Will rerun them later, when extended testing pipline finishes

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
http-advanced failure happened due to backporting error, should be fixed in the current version

**Review by mjurc — APPROVED** [review]
The CI failures are not related to this MR, but I wouldn't say they're caused by bad health of clusters - I cannot see anything wrong with them atm.

**Pull request merged**
