### PR TITLE
Bump QE Test Framework to 1.4.0.Beta4

### PR DESCRIPTION
**Pull request by gtroitsk**
### Summary

- Bumps test framework to 1.4.0.Beta4

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by gtroitsk** [comment]
run tests

**Comment by michalvavrik** [comment]
@gtroitsk JVM failure is a known one, but OCP failures are quite scary, can you investigate or re-run if you think it will help?

**Comment by gtroitsk** [comment]
> @gtroitsk JVM failure is a known one, but OCP failures are quite scary, can you investigate or re-run if you think it will help?

Sure, I will have a look at it today or tomorrow morning

**Review by michalvavrik — APPROVED** [review]
Failures are not related.

**Pull request merged**
