### PR TITLE
[3.8] Update/framework 1.4.8

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary
Update framework to 1.4.8

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
`java.lang.NoSuchMethodError: 'java.lang.String io.strimzi.test.container.StrimziKafkaContainer.getClusterId()'` seems related

**Comment by fedinskiy** [comment]
@michalvavrik fixed this

**Review by michalvavrik — APPROVED** [review]
changes makes sense, thank you

**Comment by michalvavrik** [comment]
@fedinskiy maybe we should run OCP first, anyway I don't anticipate issues

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
`OpenShiftFileSystemConfigMapConfigIT` failure in native probably not related.

**Pull request merged**
