### PR TITLE
Native Stork refactor

### PR DESCRIPTION
**Pull request by pjgg**
The current native scenario is too heavy in terms of memory and CPU usage.
This commit disables the current scenario for native mode and also create a new simpler scenario
in order to validate native execution

### CODE REVIEW

**Comment by pjgg** [comment]
run tests

**Comment by rsvoboda** [comment]
CI for OpenShift fails

**Comment by pjgg** [comment]
run tests

**Comment by pjgg** [comment]
run tests

**Comment by pjgg** [comment]
run tests

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
