### PR TITLE
[3.2] Test Vert.x pool metric for rejected submissions to the pool

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

backports https://github.com/quarkus-qe/quarkus-test-suite/pull/1551

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by mocenas** [comment]
There are missing changes from the orignal PR, in the "AbstractVertxIT" test. 3.2 branch has a bit different file organization, but these changes should be backproted as well:
https://github.com/quarkus-qe/quarkus-test-suite/pull/1551/files#diff-8ebc1b8c51602e5db66fb5f18cee1c18bbaec7ab9f26499e9e04595e7d53f558R51
https://github.com/quarkus-qe/quarkus-test-suite/pull/1551/files#diff-8ebc1b8c51602e5db66fb5f18cee1c18bbaec7ab9f26499e9e04595e7d53f558R125

**Comment by michalvavrik** [comment]
`AbstractVertxIT` differs because it was refactored between 3.2 and main. https://github.com/quarkus-qe/quarkus-test-suite/pull/1551/files#diff-8ebc1b8c51602e5db66fb5f18cee1c18bbaec7ab9f26499e9e04595e7d53f558R51 is already tested by `ThreadPoolIT`. I added it to `AbstractVertxIT` so that I have argument about native mode and OpenShift mode, but it honestly makes no difference.

I'll push that one line.

**Comment by michalvavrik** [comment]
Addressed both diffs.

**Comment by michalvavrik** [comment]
native failure `Failed to pull builder image 'quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.0-java17'` is CI related, as I'm not really changing anything related to native except for one line of metric that is there always, I think it's safe to merge

**Pull request merged**
