### PR TITLE
[2.7] Bump to Quarkus 2.7.7.Final

### PR DESCRIPTION
**Pull request by jsmrcka**
Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jsmrcka** [comment]
OCP runs:
- https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ci-distributed-ts-jvm-ocp-4/5/ - 3 failures
- https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ci-distributed-ts-native-ocp-4/5/ - GREEN

**Comment by rsvoboda** [comment]
We should have those fails also eliminated, pls investigate and try to fix TS / FW.

**Comment by mjurc** [comment]
* `OperatorOpenShiftInfinispanCounterIT` was caused by https://github.com/quarkus-qe/quarkus-test-framework/pull/667
* `OpenShiftApiServerConfigMapConfigIT` was caused by env issues in cluster - I am unable to reproduce anymore
* same for `OperatorOpenShiftAmqStreamsKafkaStreamIT` - this seems like a flake

**Comment by rsvoboda** [comment]
Thanks @mjurc, can you pls release FW with https://github.com/quarkus-qe/quarkus-test-framework/pull/667 fix?

**Comment by mjurc** [comment]
@rsvoboda https://github.com/quarkus-qe/quarkus-test-suite/pull/1039 release inclusion PR

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
