### PR TITLE
[3.15.2] backports bulk set1

### PR DESCRIPTION
**Pull request by jcarranzan**
### Summary

Backport bulk for the following merge requests: 

- https://github.com/quarkus-qe/quarkus-test-suite/pull/2183
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2188
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2209

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
@jcarranzan I think you didn't check PRs with `triage/backport-3.15` labels. Please kindly backport PRs of other people as well.

**Comment by jcarranzan** [comment]
> @jcarranzan I think you didn't check PRs with `triage/backport-3.15` labels. Please kindly backport PRs of other people as well.

Sure I can do that.
Anyway,  there is still some bulk in progress, maybe I will backport all together in a couple of days.

**Comment by michalvavrik** [comment]
btw now that I look at it, please us `-x` option when you do cherry-picks as there is no history in your commit descriptions.

**Comment by jedla97** [comment]
As this it targeting 3.15.2, shouldn't some of these test fail? As we have still have 3.15.1 in pom and I don't see update of Quarkus version here.

**Comment by michalvavrik** [comment]
> As this it targeting 3.15.2, shouldn't some of these test fail? As we have still have 3.15.1 in pom and I don't see update of Quarkus version here.

+100, I'd like to see tests failing

**Comment by jedla97** [comment]
> In pom is <quarkus.platform.version>3.15.999-SNAPSHOT</quarkus.platform.version>

Forget about it's build with snapshot. In that case it's ok from my side that test are passing. Thanks for checking it out

**Review by jedla97 — CHANGES_REQUESTED** [review]
> btw now that I look at it, please us -x option when you do cherry-picks as there is no history in your commit descriptions.

@jcarranzan can you do again cherry pick but with `-x` parameter, and force push this branche. Also please don't forget to remove labels from original PR

Also just note, when we finish development of the test for 3.15.2 I'll do backport for all marked PR (at least I put it on my list)

**Review by jedla97 — APPROVED** [review]
Missed the force push sorry.

Anyway seems good to me. I remove the backport label on mentioned issues

**Pull request merged**
