### PR TITLE
Add reactive counterparts for selected Monitoring modules

### PR DESCRIPTION
**Pull request by kshpak**

### CODE REVIEW

**Review by jsmrcka — CHANGES_REQUESTED** [review]
Rename tests to `*ReactiveIT` to make them better distinguishable from their non-reactive counterparts.

**Comment by kshpak** [comment]
> Rename tests to `*ReactiveIT` to make them better distinguishable from their non-reactive counterparts.

Good catch. PR updated

**Review by jsmrcka — APPROVED** [review]

**Comment by jsmrcka** [comment]
run tests

**Comment by jsmrcka** [comment]
Failures in native are unrelated to this PR (addressed in https://github.com/quarkusio/quarkus/issues/22275).

**Pull request merged**
