### PR TITLE
3.15 backports bulk

### PR DESCRIPTION
**Pull request by mjurc**
### Summary

* Adding a missing commit from https://github.com/quarkus-qe/quarkus-test-suite/pull/2072/
* https://github.com/quarkus-qe/quarkus-test-suite/pull/2134
* https://github.com/quarkus-qe/quarkus-test-suite/pull/2135

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by mjurc** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]
Lgtm; lately, we backport with `-x` option like `git cherry-pick -x` (for next time)

**Comment by mjurc** [comment]
@michalvavrik I've updated it, sorry about that, I completely forgot

**Comment by mjurc** [comment]
run tests

**Comment by michalvavrik** [comment]
np

**Pull request merged**
