### PR TITLE
Update Infinispan to version 15

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

Upstream did it some time ago: https://github.com/quarkusio/quarkus/pull/39389

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
Windows CI fails due to unrelated issue "java.lang.NoClassDefFoundError: io/quarkus/bootstrap/model/AppDependency" (also on main)

**Comment by fedinskiy** [comment]
Same goes for the second Linux run and OCP JVM run

**Review by michalvavrik — APPROVED** [review]
thanks

**Comment by michalvavrik** [comment]
OCP tests seem quite alright.

**Comment by michalvavrik** [comment]
https://github.com/quarkus-qe/quarkus-test-framework/pull/1212 seems to fix CI failures

**Pull request merged**
