### PR TITLE
Fix Spring Data compilation after Spring bump upstream

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

After https://github.com/quarkusio/quarkus/pull/40344 compilation of this project fails. This is expected as described in the PR description. This PR does not fix all the test failures, just `SpringDataCompositeEntityIT` and compilation.

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
hey @jedla97 this PR only fixes compilation of TS, after the bump there are tests failing that I still must report and handle. But I'd like to have TS compiled because it blocks other PRs (like mine :-)). So please review as "compilation hotfix".

**Review by jedla97 — APPROVED** [review]
It makes sense to at least compile the module.

**Comment by michalvavrik** [comment]
There is something very wrong with CI, I think it's a GitHub issues. Thanks for review. I'll just merge it.

**Comment by michalvavrik** [comment]
I run validation checks locally.

**Comment by jedla97** [comment]
> There is something very wrong with CI, I think it's a GitHub issues. Thanks for review. I'll just merge it.

It's GH issue at least by status https://www.githubstatus.com/ so probably no action tonight :cry:

**Comment by michalvavrik** [comment]
> > There is something very wrong with CI, I think it's a GitHub issues. Thanks for review. I'll just merge it.
> 
> It's GH issue at least by status https://www.githubstatus.com/ so probably no action tonight 😢

interesting, I didn't know that, thanks!

**Pull request merged**
