### PR TITLE
Disable openshift extension deploy on snapshot

### PR DESCRIPTION
**Pull request by jsmrcka**
### Summary

- Profile `deploy-to-openshift-using-extension` is requested by Quarkus-test-framework when is running an Operator scenario
- Disable several scenarios on OCP Upstream coverage due to an Upstream [issue](https://github.com/quarkusio/quarkus/issues/29921)

Replaces https://github.com/quarkus-qe/quarkus-test-suite/pull/952.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jsmrcka** [comment]
run tests

**Comment by jsmrcka** [comment]
run tests

**Comment by rsvoboda** [comment]
why don't we use just `quarkus.openshift.deploy=true`?

```
quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/ExtensionOpenShiftQuarkusApplicationManagedResource.java:
    private static final String QUARKUS_PLUGIN_DEPLOY = "-Dquarkus.kubernetes.deploy=true";
```

**Comment by jsmrcka** [comment]
Replaced with https://github.com/quarkus-qe/quarkus-test-framework/pull/633.

**Pull request closed without merging**
