### PR TITLE
Bump MySQL Docker image to 5.7.42

### PR DESCRIPTION
**Pull request by gtroitsk**
### Summary

Issue https://github.com/docker-library/mysql/issues/844 was closed

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
I read whole issue and (hopefully) important of linked issues  - yet, I can't find why you think it is fixed with 5.7.42. What I understood from context, they changed Oracle to Debian and with 5.7.42 it still doesn't work.

Anyway, I trust you tested this and therefore, if tests are passing, I think we can merge it. If we run into issues in the future, we should try `5.7.42-oracle` as that one is based on same Linux as 5.7.36.

**Comment by michalvavrik** [comment]
@gtroitsk please resolve POM conflicts, thx

**Review by michalvavrik — CHANGES_REQUESTED** [review]
I re-run CI, both runs got interrupted and failed exactly on 5.7.42. Please try Oracle one instead and add note why we are using Oracle one instead of default Linux distribution (Debian).

**Review by michalvavrik — APPROVED** [review]
LGTM

**Comment by michalvavrik** [comment]
Narayana transactions went down to lack of free space.

**Comment by gtroitsk** [comment]
Now I have mentioned that I have bad commit message. Didn't change it during testing

**Comment by michalvavrik** [comment]
I have to start checking commit messages :-) Never mind.

**Pull request merged**
