### PR TITLE
Update REST client dependency names after extension name change as the Test Suite compilation fails

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7#rest-client-gear-white_check_mark

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
Where did you see the failures?

There should be relocations in place for changed GAVs, CI is building Quarkus main with relocations:
 - https://github.com/quarkus-qe/quarkus-test-suite/blob/main/.github/workflows/ci.yml#L25
 - https://github.com/quarkus-qe/quarkus-test-suite/blob/main/.github/workflows/daily.yaml#L27

We are processing 3.2.10 TD, so I'd rather wait with this change till 3.2.10 is processed.
Plus the name change shouldn't by breaking one thanks to relocations.

**Comment by michalvavrik** [comment]
> Where did you see the failures?

locally

> We are processing 3.2.10 TD, so I'd rather wait with this change till 3.2.10 is processed.

3.2.10 has it's own branch, I don't think it's sound argument as if you do a backport, you can just tweak one name. I'll respect if it's important for you

> Plus the name change shouldn't by breaking one thanks to relocations.

I never needed relocations till now. There is not a single word about them in https://github.com/quarkus-qe/quarkus-test-suite/blob/main/README.md so it is breaking change for me. I can adapt, but disagree.

**Comment by rsvoboda** [comment]
3.2.10 - there will be backports from main to 3.2 branch

locally - you need to enable relocations module  ... e.g. `mvnd clean install -Dquickly -Prelocations  -Dno-test-modules`

relocations - https://github.com/quarkusio/quarkus/tree/main/relocations
They are used quite a lot, especially when extensions move to quarkiverse

**Comment by michalvavrik** [comment]
> 3.2.10 - there will be backports from main to 3.2 branch
> 
> locally - you need to enable relocations module ... e.g. `mvnd clean install -Dquickly -Prelocations -Dno-test-modules`
> 

ok

> relocations - https://github.com/quarkusio/quarkus/tree/main/relocations They are used quite a lot, especially when extensions move to quarkiverse

I don't see in Quarkus [README](https://github.com/quarkusio/quarkus/blob/main/README.md) or [CONTRIBUTING](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md) documents any suggestion to use relocation. I don't mind using them based on migration note for now, but if there is such a requirement for our project or Quarkus snapshot, it should be documented.

**Comment by rsvoboda** [comment]
> it should be documented

+1, please create GH issue in Quarkus repo

**Review by rsvoboda — APPROVED** [review]
LGTM

Will be merged once https://github.com/quarkus-qe/quarkus-test-suite/pulls?q=is%3Apr+is%3Aclosed+label%3Atriage%2Fbackport-3.2 are backported

**Comment by maxandersen** [comment]
> > > it should be documented
> 
> > 
> 
> > +1, please create GH issue in Quarkus repo
> 
> 
> 
> the issue should be created by someone who believes they should be used :-) I don't.
> 
> 
> 
> Let's conclude this, I'll use relocation and thank you for comments and information.

If you want to have a branch that works with both 3.2 and 3.7-8+ you'll need to have a build with relocations or a profile to handle the diff. 

I'm going to check with gsmet why we don't just always build with them enabled and just have a way to turn them of so a build is as close to what users will experience.

**Pull request merged**
