### PR TITLE
Disable tests affected by issue 38676

### PR DESCRIPTION
**Pull request by mocenas**
### Summary

Disable test affected by issue 38676.

Link to the issue https://github.com/quarkusio/quarkus/issues/38676.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by michalvavrik — APPROVED** [review]
LGTM

**Comment by michalvavrik** [comment]
@mocenas Mike said he will provide PR today, I think we should wait till tomorrow, but I'll leave decision on you. It's very easy to revert this, so it's not important.

**Comment by mocenas** [comment]
I agree we should wait until tomorrow. If the fix is going to be so soon.

**Comment by michalvavrik** [comment]
superseded by https://github.com/quarkusio/quarkus/pull/38694

**Pull request closed without merging**
