### PR TITLE
Use only fake domain in our tests

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

- closes https://github.com/quarkus-qe/quarkus-test-suite/issues/2111

The `ReactiveRestClientProxyIT` test really talked to `http://example.com`, now no external communication to `example.com` is run, however we assert that correct host was proxied by passing `$host` via Nginx back to the test.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
There doesn't seem to be a sense to rerun OCP now, I'll try it tomorrow as the cluster is in a bad shape.

**Comment by michalvavrik** [comment]
I thought about it and what we need to test is that proxy options are set correctly, not the redirect to external domain.

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
@mocenas OCP native run didn't fail, I canceled it manually because it was started when OCP cluster was down and now it is waiting in a queue. I won't merge this till it is green, so please review when you get a time. Thanks

**Comment by mocenas** [comment]
> I thought about it and what we need to test is that proxy options are set correctly, not the redirect to external domain.

I thought about it too. It "would be nice" if we could do an E2E test to verify that communication though proxy works. But as you states, we want to test connection and options-passing to the proxy, not proxy's ability to forward it outside.

**Review by mocenas — APPROVED** [review]
LGTM

**Comment by michalvavrik** [comment]
I have re-triggered OCP native manually in Jenkins several times, it seems like it fails randomly on OOM and failing tests are changing. I can see periodic OCP native CI is also failing over OOM (among other) so I dare say it is not related (also not sure how could changes here cause OOM). For that reason I think it should be safe to merge.

**Pull request merged**
