### PR TITLE
Enable several disabled tests, remove others

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

- Enable tests, which were disabled due to issues, which are now fixed (one of them required changes)
- Remove a test which was disabled since Quarkus 2 era

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
@fedinskiy formatting check didn't pass

Several `DisabledOnAarch64Native` were removed, do you have run of the branch in in the lab with aarch64? fyi @mjurc 
(@mjurc shouldn't we have aarch64 triggered by "run tests" phrase, we should have QQE for it)

This PR seems to be suitable for "run tests" phrase

**Comment by fedinskiy** [comment]
@rsvoboda 
formatting was fixed, aarch64 running is a planned next step. I do not think, that we can run aarc64 tests manually, but would be glad to be proved wrong

**Comment by michalvavrik** [comment]
@fedinskiy I don't need a proof (link, job run etc.), but I need you to check that enabled tests will suceed on Aarch64, could you check please?

**Comment by michalvavrik** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]

**Comment by fedinskiy** [comment]
Brotli: this works: `mvn clean verify -Popenshift -Dit.test=OpenShiftBrotli4JIT -Doc.reruns=0`, but requires adding native brotli library for arm. Probably this is also going to affect IBM folks, but let's solve problems, when they arise.

**Comment by michalvavrik** [comment]
run tests

**Pull request merged**
