### PR TITLE
Use single HTTP server for gRPC services

### PR DESCRIPTION
**Pull request by gtroitsk**
### Summary

Solves issue https://github.com/quarkus-qe/quarkus-test-suite/issues/1373

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by gtroitsk** [comment]
I will wait to run OC tests as it has failed some. See https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/view/all/job/quarkus-main-rhel8-jdk11-openshift-ts-jvm/2/#showFailuresLink

**Comment by michalvavrik** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]
LGTM, but let's wait till I manage to resolve OpenShift issues. I'm going to merge this myself when it's done.

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
Rebased on main in order to get OCP fixed.

**Comment by michalvavrik** [comment]
I tested it and `io.quarkus.ts.opentelemetry.reactive.OpenShiftOpentelemetryReactiveIT.testContextPropagation` native failure is not related.

**Pull request merged**
