### PR TITLE
Cover Continuous Testing

### PR DESCRIPTION
**Pull request by Sgitario**
Basic coverage of Continuous testing feature with:
- Detection of new tests
- Detection of changes on existing sources

### CODE REVIEW

**Comment by Sgitario** [comment]
Depends on https://github.com/quarkus-qe/quarkus-test-suite/pull/40

**Comment by Sgitario** [comment]
@pjgg would you mind taking a look into this PR please? Thanks!

**Comment by Sgitario** [comment]
@kshpak adding you as reviewer as I see Rostislav assigned this epic task to both of us.

**Comment by kshpak** [comment]
WIP.
@Sgitario what about adding a "build" profile for the quick install of the test framework, like quarkus main does "mvn clean install -Dquickly"
https://github.com/quarkusio/quarkus/blob/bee36ae7679aaa8026a72da19ef2c0c3ac779035/pom.xml#L144

P.S -DskipTests also work, but I think unified experience between quarkus main build and test framework build is a good thing.

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
Serverless is behaving slow... we need to increase the timeout for service start.

**Comment by Sgitario** [comment]
Tests are working fine. The failures are unrelated to these changes. Merging.

**Pull request merged**
