### PR TITLE
Update native image builders - use version 22.2

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Updates GraalVM/Mandrel version to 22.2.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jsmrcka** [comment]
@michalvavrik Could you pls check the CI failures?
At least the `lifecycle-application` module in [1] looks suspicious.
```
00:02:23 java.lang.IllegalAccessError: class io.quarkus.runner.AutoFeature (in unnamed module @0x99d3150) cannot access class org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport (in module org.graalvm.sdk) because module org.graalvm.sdk does not export org.graalvm.nativeimage.impl to unnamed module @0x99d3150
```
[1] https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-openshift-ts-native/4/consoleFull

**Comment by michalvavrik** [comment]
luckily I can reproduce this, I'll working on it

**Comment by michalvavrik** [comment]
OC: In fact, previous state didn't make sense, we should define Mandrel version next to RHBQ to keep them compatible. Fixed. https://github.com/quarkusio/quarkus/issues/26640#issuecomment-1180119429

Other CI failures were from JVM build, so they shouldn't be related.

**Comment by michalvavrik** [comment]
I went through the failures and I believe they are not related. Let see native build number 12 (from 4.8), it contains all of these failures apart of the `OpenShiftJSONCloudEventsOverProdAmqpIT` that failed possibly over network issue (`oc: Unable to connect to the server`).

**Comment by michalvavrik** [comment]
I plan no further changes.

**Review by jsmrcka — APPROVED** [review]

**Pull request merged**
