### PR TITLE
Disable on Native

### PR DESCRIPTION
**Pull request by jcarranzan**
### Summary

As I described in the TP (https://github.com/quarkus-qe/quarkus-test-plans/blob/9c6b5a01882dd0a96fa0fad9019eeb479760e22e/QUARKUS-4221.md?plain=1#L11) , this is supported only for JVM. 

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by michalvavrik — APPROVED** [review]
LGTM, I suspect imports are not sorted, but that's the CI problem. Thanks for the fix.

**Review by michalvavrik — APPROVED** [review]

**Comment by rsvoboda** [comment]
I understand the disable in dev mode, but why for prod mode?

Keycloak team is the trigger, but we aim to support this for any customer. And having cli utilities compiled into native can be handy for them - one binary / no need for java runtime / faster boot

**Comment by michalvavrik** [comment]
> that already mention some incompatibilities and workaround https://quarkus.io/guides/picocli#native-mode-support

just to be clear, I don't believe there are any incompatibilities. what the guide says is that "if we missed something with future bumps, here is trick that fixes native mode". but it will be a bug anyway, so if there is something not working, file the issue.

**Comment by michalvavrik** [comment]
anyway, I suggest to merge this and give @jcarranzan time to investigate. there is no point in having failing daily builds.

**Comment by michalvavrik** [comment]
because it follows current TP, so let's change TP first...

**Comment by michalvavrik** [comment]
let's continue here https://github.com/quarkus-qe/quarkus-test-suite/pull/2043#pullrequestreview-2325551851

**Pull request closed without merging**
