### PR TITLE
[3.8] Bump test framework version to 1.4.10

### PR DESCRIPTION
**Pull request by gtroitsk**
### Summary

Bump framework to 1.4.10

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jedla97** [comment]
run tests

**Review by jedla97 — APPROVED** [review]
LGTM! Lets wait for CI

**Comment by gtroitsk** [comment]
@jedla97 I see failures in JVM are all related to Quarkus cli update command. FW `1.4.10` release doesn't contain any changes for cli. @mocenas Can you please have a look at failures? I think it is related to bumping quarkus version to 3.8.6

**Comment by jedla97** [comment]
@gtroitsk Thanks for info!

Probably for windows CI the test should have `@Tag("quarkus-cli")` to not run them on GH action as we don't setting the quarkus cli here yet

**Comment by mocenas** [comment]
Looking into it. Windows tests doesn't have `Tag("quarkus-cli")` so they run on windows, even when win doesn't have quarkus CLI command.

Build on JVM fail because quarkus update test is made only for RHBQ.

Yes this was enabled by update to 3.8.6, because for <=3.8.5 cli update tests are disabled because of some failure.

I will create fix PRs for these. IMHO it is unrelated to this, and this PR can be merged.

**Comment by gtroitsk** [comment]
> @gtroitsk Can you check why `KafkaGratefulShutdownIT.shouldWaitForMessagesWhenGratefulShutdownIsEnabled` failing?
> 
> The failing of `MssqlTransactionGeneralUsageIT.testTransactionRecovery` is because of the #1905 I'll create PR for 3.8 backports tomorrow so this will be fixed

I will have a look tomorrow

**Review by jedla97 — APPROVED** [review]

**Pull request merged**
