### PR TITLE
[3.8] Backports 4th of September

### PR DESCRIPTION
**Pull request by jedla97**
### Summary

Backports for preparation to 3.8.6 testing

Backported PRs:

- https://github.com/quarkus-qe/quarkus-test-suite/pull/1854
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1881
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1899
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1896
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1905
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1910
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1919
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1941
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1961
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1949
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1972
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1968
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1962

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by rsvoboda — APPROVED** [review]
GitHub CI is green, approving

**Comment by rsvoboda** [comment]
@jedla97 what about OpenShift runs? Are they needed?

**Comment by jedla97** [comment]
@rsvoboda I will run them just to check. Also I want to add other backports for 3.8.6, there were some recent merge.

**Comment by jedla97** [comment]
Waiting for https://github.com/quarkus-qe/quarkus-test-suite/pull/1972 to be merged, after that I will rebase, cherry pick and push

**Comment by gtroitsk** [comment]
> Waiting for #1972 to be merged, after that I will rebase, cherry pick and push

https://github.com/quarkus-qe/quarkus-test-suite/pull/1972 was merged, you can rebase PR

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
The https://github.com/quarkus-qe/quarkus-test-suite/pull/1963 and https://github.com/quarkus-qe/quarkus-test-suite/pull/1970 are not part of this backport as they are failing and fixes are not yet backported to 3.8 branch

**Comment by jedla97** [comment]
run tests

**Comment by rsvoboda** [comment]
DownloadResourceIT failed because oidcdisable.properties was not in 3.8 branch. I think FW should complain about such scenario so the root cause is more obvious.

**Comment by jedla97** [comment]
run tests

**Review by rsvoboda — APPROVED** [review]
Thanks for the back-port effort @jedla97. It's good to see green CI for all these changes!

**Pull request merged**
