### PR TITLE
[3.2] Bump htmlunit to 3.5.0

### PR DESCRIPTION
**Pull request by mjurc**
### Summary

* Updating htmlunit to 3.5.0, along with relocations required by the htmlunit migration guide (https://www.htmlunit.org/migration.html).

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by mjurc** [comment]
run tests

**Comment by mjurc** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]
LGTM. Let's wait for https://github.com/quarkus-qe/quarkus-test-suite/pull/1385 as I don't fancy to re-run the whole CI in case of conflicts there.

**Comment by mjurc** [comment]
Failures unrelated; merging

**Pull request merged**
