### PR TITLE
Rename some deprecated `quarkus.health` properties to `quarkus.smallrye-health`

### PR DESCRIPTION
**Pull request by jedla97**
### Summary

Renaming 
- `quarkus.health.extensions.enabled` → `quarkus.smallrye-health.extensions.enabled`
- `quarkus.health.openapi.included` → `quarkus.smallrye-health.openapi.included`

For more info see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#smallrye-health

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
OC seems having problems to find `999-SNAPSHOT`  `quarkus-test-preparer` leaving this problam to Monday

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
@jedla97 I'll deal with OCP failures, but can you rebase please? I'd like to see same failures on current main (which I totally expect from what I read, but it's just surprising).

**Comment by michalvavrik** [comment]
run tests

**Comment by rsvoboda** [comment]
https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/redpanda.20images.20not.20available

Fix PR is merged

**Comment by rsvoboda** [comment]
Fix will be in next community push of Quarkus 999-SNAPSHOT, I think that happens once per day

**Comment by michalvavrik** [comment]
I need to adjust our internal Nexus to fix OCP and I need to go offline for few hours. I'll deal with OCP in the evening.

**Comment by rsvoboda** [comment]
https://github.com/quarkusio/quarkus/actions/workflows/deploy-snapshots.yml

**Comment by rsvoboda** [comment]
I can trigger it, I guess I will so the CI work is unblocked

**Comment by rsvoboda** [comment]
@jedla97 @michalvavrik new Quarkus main bits are deployed

@jedla97 pls rebase the PR

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
run tests

**Comment by michalvavrik** [comment]
>For the GH error, I see same on daily so it's not related.

yeah, I'll look tomorrow.

> For the GH error, I see same on daily so it's not related. For openshift it was fixed by #2237

I trust you, but could you just rebase? I'd like to see OCP CI at any rate in _some_ PR, so it can be this one as well.

**Comment by michalvavrik** [comment]
No, I can see that OCP CI run, so it' s fine, let me merge.

**Review by michalvavrik — APPROVED** [review]
changes lgtm, thanks for your patience

**Pull request merged**
