### PR TITLE
Enable Hibernate Reactive tests for PostgreSQL, MariaDB and MySQL

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

https://github.com/quarkusio/quarkus/pull/31454 is merged, so we should be testing Hibernate Reactive for PostgreSQL, MariaDB and MySQL, while MsSQL and Oracle will work in next release https://github.com/quarkusio/quarkus/issues/32102#issuecomment-1482523629.

Changes:

- added cascade constraint to init scripts as previously these `DROP TABLE` didn't work and logged constraint violation (correct behavior)
- migrated M:N relation between `Author` and `Book` to unidirectional `@OneToMany`. Previously we had some hybrid between unidirectional and bidirectional mapping that doesn't work anymore due to casting exception. In my understanding that's absolutely correct behavior - for bidirectional mapping you need entity on the other side, while we were using primitive type without `@ManyToOne` but still set `@OneToMany#mappedBy`.
- changed `MariaDB102Dialect` to `MariaDBDialect` as former is not supported anymore and we don't use legacy database
- Spring Web Reactive needs to use `@WithSession` due to recent changes in Panache https://github.com/quarkusio/quarkus/pull/29761, `@WithSession` does not support `Multi`
-  `@ReactiveTransactional` has been marked for removal, so I changed one of 2 usages in Spring Web Reactive ti `@WithTransaction` in order to have tested preferred way

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
Debugging OC failures.

**Comment by michalvavrik** [comment]
Opened issue as I wasted loads of time on this https://github.com/quarkusio/quarkus/issues/32040.

**Comment by michalvavrik** [comment]
run tests

**Review by fedinskiy — APPROVED** [review]

**Comment by michalvavrik** [comment]
I'll check native (and don't do anything till it's fixed) :-/

**Comment by rsvoboda** [comment]
It is! You can drop `like` from your statement :)

**Comment by michalvavrik** [comment]
As for OpenShift failures, they all succeeded when run from my workstation (in terms of Hibernate Reactive modules), so there must be some difference when run from CI, I am on it.

**Comment by michalvavrik** [comment]
Created upstream issue for native failure: https://github.com/quarkusio/quarkus/issues/32114

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
There is one OpenShift JVM mode failure now - `OpenShiftWebSocketsClientIT` which is not related as this PR doesn't touch that module, so I'll go ahead and merge it.

**Pull request merged**
