### PR TITLE
Add test coverage for issue 36402

### PR DESCRIPTION
**Pull request by mocenas**
for branch 3.2

### Summary

Copy of https://github.com/quarkus-qe/quarkus-test-suite/pull/1508 for branch 3.2

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [X] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [X] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
The flow is to add backport 3.2 label on the original PR, issues should be backported in a bulk
CC @michalvavrik

**Comment by mocenas** [comment]
> The flow is to add backport 3.2 label on the original PR, issues should be backported in a bulk CC @michalvavrik

OK, I've added label to original PR. should I make this a draft and backport it when all issues are covered? @rsvoboda

**Comment by rsvoboda** [comment]
Please close this one, the idea is to have control over the things that go into 3.2 branch and have the backports reviewed by the gatekeeper. Bulks also save some resources on CI side and should allow better scaling of the work.

**Comment by michalvavrik** [comment]
> Please close this one, the idea is to have control over the things that go into 3.2 branch and have the backports reviewed by the gatekeeper. Bulks also save some resources on CI side and should allow better scaling of the work.

+1; _You Shall Not Pass_ @mocenas :-)

> OK, I've added label to original PR. should I make this a draft and backport it when all issues are covered? @rsvoboda

It's fine if you do bulk backport PR when 3.2 test coverage is finished and request my review, thank you. We will need to run OCP tests as I forgot to run one for your PR. If for any reason you want me to do backports, please ping me, it's my duty anyway. One way or another, please get me involved again.

**Comment by michalvavrik** [comment]
Truth be told I also didn't mention until now that original PR has 3 commits, shame on me. Good that you squashed it for backports.

**Pull request closed without merging**
