### PR TITLE
Cosmetic changes on datagrid 8.4 integration

### PR DESCRIPTION
**Pull request by pjgg**
### Summary

- Profile `deploy-to-openshift-using-extension` is requested by Quarkus-test-framework when running an Operator scenario

Please select the relevant options.

- [X] Refactoring
- [X] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [X] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jsmrcka** [comment]
run tests

**Comment by jsmrcka** [comment]
The CI failure in `Quarkus QE TS: Messaging: Reactive Kafka` is unrelated, caused by https://github.com/quarkusio/quarkus/issues/29954 and should be resolved by https://github.com/quarkus-qe/quarkus-test-suite/pull/956.

**Comment by pjgg** [comment]
run tests

**Review by jsmrcka — APPROVED** [review]
LGTM.

The OCP deployment issue has been addressed in https://github.com/quarkus-qe/quarkus-test-framework/pull/633.

**Pull request merged**
