### PR TITLE
Use OpenTelemetry extension in Build-tiime Analytics module as OpenTracing is deprecated and not released yet

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Fixes CI. https://github.com/quarkus-qe/quarkus-test-suite/pull/1519 follow-up

https://docs.quarkiverse.io/quarkus-smallrye-opentracing/dev/index.html says we should use OpenTelemetry. There is no deeper logic why this module used OpenTracing extension (like product requirement or RH ticket etc.), so here we can safely replace it with preferred version.

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jcarranzan** [comment]
It looks good to me, waiting for CI jobs

**Comment by jcarranzan** [comment]
Native build failed, is it expected?

**Comment by michalvavrik** [comment]
> Native build failed, is it expected?

No, but it failed over _Terminating due to java.lang.OutOfMemoryError: GC overhead limit exceeded_ and I don't believe OpenTelemtry made the difference. It's as simple as: the test is building native executable image with too many extensions and you can only hope GH CI runner will have enough of space. I'd suggest to watch daily builds and if it happens repeatedly, make lighter executable in GH.

**Comment by michalvavrik** [comment]
btw. I totally experienced it in past...

**Review by jcarranzan — APPROVED** [review]

**Pull request merged**
