### PR TITLE
Fix OpentelemetryReactiveIT#testSchedulerTracing by updating operation name

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Failures go down to https://github.com/quarkusio/quarkus/pull/35989#issuecomment-1835979200, let see if that was intentional, I guess not. But we should fix tests and eventually revert it with upstream fixes.

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
cc @mjurc this is one of failures we saw in OCP failures and also in daily build failures. I'm going to wait if upstream folk will alter it (as operation name is likely to change again), but I also think there is no point for not merging fix if they don't fix it today. can you review this as I already run tests? I'd only merge it if upstream don't change EOB. Choice is yours, we can wait till next week as well.

**Comment by michalvavrik** [comment]
I talked to Martin Kouba and he things it is rather unlikely that they will change anything today. We should fix our tests, so I'll request review. @mocenas wanna look?

**Comment by michalvavrik** [comment]
> The changes are IMHO OK as a hotfix, but I would like to have a TODO/FIXME/comment with a link to the issue and description why do we do it this way.

will add comment in a minute, but please take note that there is 9 successful checks. we don't need to re-run everything because of one comment, probably validation and that's it. Thanks

**Review by mocenas — APPROVED** [review]
LGTM

**Pull request merged**
