### PR TITLE
Rename rest-client extension

### PR DESCRIPTION
**Pull request by mocenas**
### Summary

`quarkus-rest-client` extension got renamed in the upstream to `quarkus-resteasy-client`. Rename it in analytics test.
Rename was done in PR https://github.com/quarkusio/quarkus/pull/38190 

This should be renamed in quarkus 3.7 forth. Reactive version will probably also be renamed the future.

Please select the relevant options.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
Isn't this handled by https://github.com/quarkus-qe/quarkus-test-suite/pull/1617?

**Comment by mocenas** [comment]
> Isn't this handled by #1617?

It is. Sorry I didn't looked at that one. Thing is, even relocations does not fix it now. So either this one or #1617 should be merged to fix this problem. Our GH daily pipeline is already failing because of this. Compiling quarkus locally with -Prelocations does not help.

**Review by michalvavrik — APPROVED** [review]
> > Isn't this handled by #1617?
> 
> It is. Sorry I didn't looked at that one. Thing is, even relocations does not fix it now. So either this one or #1617 should be merged to fix this problem. Our GH daily pipeline is already failing because of this. Compiling quarkus locally with -Prelocations does not help.

that's compelling reason

**Comment by michalvavrik** [comment]
to sum it up @rsvoboda - 99 % of cases this PR will cause no conflicts (it changes names of 3 strings inside build time analytics modules, no pom), I think we need to avoid failing tests so that daily build is run in full. It's different to my PR. I'll merge it, if you disagree, please click to "revert" and I'll approve it. Thanks

**Pull request merged**
