### PR TITLE
Bump framework version to 1.4.0.Beta8

### PR DESCRIPTION
**Pull request by gtroitsk**
### Summary

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by gtroitsk** [comment]
run tests

**Comment by gtroitsk** [comment]
OC failures are related with migration to using Deployments instead of DeploymentConfig. 
Amq tests fails because service name is not matched, currently `amq:latest` must be ` ${SERVICE_NAME}:latest` or labels must be changed to `amq`. Please see [amq-template ](https://github.com/quarkus-qe/quarkus-test-framework/commit/d4d2d2ed96d0f61e8631a7f8de5261dd01ce3691#diff-e40de9d8ff5cea88824b5ca16bddb070020924a0382b4960e414ab22be7e408dR45)

Other two tests failures must be resolved by https://github.com/quarkus-qe/quarkus-test-suite/pull/1645

**Comment by michalvavrik** [comment]
> OC failures are caused by migration to using Deployments instead of DeploymentConfig. Amq tests fails because service name is not matched, currently `amq:latest` must be ` ${SERVICE_NAME}:latest` or labels must be changed to `amq`. Please see [amq-template ](https://github.com/quarkus-qe/quarkus-test-framework/commit/d4d2d2ed96d0f61e8631a7f8de5261dd01ce3691#diff-e40de9d8ff5cea88824b5ca16bddb070020924a0382b4960e414ab22be7e408dR45)
> 
> Other two tests failures must be resolved by #1645

Hey @fedinskiy please have a look next week. @gtroitsk needs this merged in order to finish his task this week, so I'm going to merge it.

Which means we can expect OpenShift failures in weeky's cc @mjurc

**Review by michalvavrik — APPROVED** [review]

**Comment by michalvavrik** [comment]
As I can see that #1645 has backport label, I'm adding it here as well.

**Pull request merged**
