### PR TITLE
Verify, that VertX pool metrics are being collected

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

Coverage for Full support of Vertx metrics, see https://issues.redhat.com/browse/QUARKUS-2830 for details.
Test plan: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-2830.md

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [x] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
Changed to Michal, Josef is on pto this week

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
@michalvavrik the CI is green

**Comment by michalvavrik** [comment]
> @michalvavrik the CI is green

hurrah, I'll look this afternoon

**Review by michalvavrik — APPROVED** [review]
Fine job.

**Pull request merged**
