### PR TITLE
Cover GitOps friendly Kubernetes additions

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

Quarkus 3 allows making K8s manifests more Git-friendly [1]
We cover them with these changes, with a single exception[2]

[1] https://github.com/quarkusio/quarkus/pull/31373
[2] https://github.com/quarkusio/quarkus/issues/34673

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [x] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
I've seen these OC failures today already, they are not related to changes.

**Comment by michalvavrik** [comment]
More specifically, I have seen same failures in run OC JVM run number 90, so I know `OpenShiftConfigSourcePriorityIT` failure is not related. On the other hand, `OpenShiftConfigSourcePriorityIT` is needed for this PR and we can't test it. I can reproduce issue on our main branch and it is caused by `quarkus.openshift.env.vars.side-note=side note environment variable`. It is quite late, not sure if I'm going to report or analyze it today.

**Comment by fedinskiy** [comment]
@michalvavrik I will handle these changes here: https://github.com/quarkus-qe/quarkus-test-suite/pull/1314.
I suggest to keep this PR open, until the second one is merged

**Comment by michalvavrik** [comment]
Ok @fedinskiy but it looks like bug in Quarkus to me. I'm just trying to create standalone reproduce. If you already know where the problem is, I will stop.

**Comment by michalvavrik** [comment]
On second thought, I'm going to sleep.

**Comment by fedinskiy** [comment]
run tests

**Comment by michalvavrik** [comment]
Failure related `File kubernetes.yml does not contains commit ids! ==> expected: <true> but was: <false>`

**Comment by fedinskiy** [comment]
This is very weird behavior, which I can not reproduce manually on the latest 999-SNASHOT

run tests

**Comment by fedinskiy** [comment]
run tests

**Comment by michalvavrik** [comment]
Hmm, still there :-/

**Comment by fedinskiy** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]
LGTM

**Pull request merged**
