### PR TITLE
[3.2] Backports and Quarkus bump to 3.2.9

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Contains:

- https://github.com/quarkus-qe/quarkus-test-suite/pull/1524
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1504
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1508
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1513
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1514
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1515
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1518
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1533
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1507
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1536

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
OCP JVM failures are flaky. I've mean to fix these 4 for ten times now, we really need to create task for it :-)

```
io.quarkus.ts.messaging.strimzi.kafka.reactive.OpenShiftAmqStreamsKafkaAvroIT.testAlertMonitorEventStream
io.quarkus.ts.messaging.strimzi.kafka.reactive.OpenShiftAmqStreamsKafkaAvroIT.batchMustBeGreaterThanSingleEvent
io.quarkus.ts.messaging.strimzi.kafka.reactive.OpenShiftStrimziKafkaAvroIT.testAlertMonitorEventStream
io.quarkus.ts.messaging.strimzi.kafka.reactive.OpenShiftStrimziKafkaAvroIT.batchMustBeGreaterThanSingleEvent
```

**Comment by michalvavrik** [comment]
I think it would be great to run general trigger over night, I think I'll take responsibility on me. @mocenas could you still review tomorrow please? If you find something, I'll make tweaks tomorrow, thank you.

**Review by mocenas — COMMENTED** [review]
I've reviewed it, although it is already merged. Found no issues.

**Comment by michalvavrik** [comment]
> I've reviewed it, although it is already merged. Found no issues.

Thanks, appreciated.

**Pull request merged**
