### PR TITLE
Updating GH actions to run quarkus cli on windows

### PR DESCRIPTION
**Pull request by TimonCzech**
### Summary

TODO

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [x] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jedla97** [comment]
Let's see if this work. Also this should be added to native win run

**Comment by jedla97** [comment]
I see it's updating only daily, for check it in PR it should be also updated in https://github.com/quarkus-qe/quarkus-test-suite/blob/main/.github/workflows/ci.yml

**Comment by TimonCzech** [comment]
@jedla97 will finish this

**Comment by michalvavrik** [comment]
There has been changes in the GH CI, you would need to adapt your PR, make sure that no test is running DEV svc and most importantly, I am not sure that `bat` will work, will it? I'd think you need `.exe`. This PR is bit old so if you are interested, please come back to it. It would be great addition.

**Pull request closed without merging**
