### PR TITLE
[3.2] Backport Docker and Podman changes for Ghost

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Backports:

- https://github.com/quarkus-qe/quarkus-test-suite/pull/1384
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1383
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1380

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
I don't really expect CI to succeed as there is too many changes (timeouts), but let see.

**Comment by michalvavrik** [comment]
run tests

**Review by mjurc — APPROVED** [review]
Exhaustive backport, looks correct to me.

Let's wait for CI anyway, please, to curb out any obvious errors that we may have missed in case there's any such.

**Comment by mjurc** [comment]
run tests

**Comment by mjurc** [comment]
Failures unrelated - merging.

**Pull request merged**
