### PR TITLE
[3.15] Bump Quarkus QE Test Framework to 1.5.6 and do backports available as of 2024/10/14

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

This PR backports:

- https://github.com/quarkus-qe/quarkus-test-suite/pull/2072
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2081
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2083
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2086
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2087
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2088

Bumps Quarkus QE Test Framework to 1.5.6 (also required by one of the backported PRs):

- https://github.com/quarkus-qe/quarkus-test-framework/pull/1370

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
OpenShift JVM failure `io.quarkus.ts.infinispan.client.OperatorOpenShiftInfinispanCountersIT` is IMO flaky and not related.

**Comment by mjurc** [comment]
run tests

**Comment by michalvavrik** [comment]
@mjurc that is about 3 time this has been done (I myself rerun something manually and then I think Fedor this). This is not constructive. Anyway, let's wait again.

**Comment by michalvavrik** [comment]
There are yet different failures in the OpenShift JVM and `OperatorOpenShiftInfinispanCountersIT` is gone.

**Comment by mjurc** [comment]
I was just reinstalling clusters in the afternoon and somebody tried to run tests, but I'm not sure which run it was, so I reran it 😅

**Comment by michalvavrik** [comment]
> I was just reinstalling clusters in the afternoon and somebody tried to run tests, but I'm not sure which run it was, so I reran the only open one with OCP tests 😅

No worry, I am just annoyed by the failures. If I ever catch golden fish, I'll wish end flakes forever.

**Review by fedinskiy — APPROVED** [review]
Failures in Openshift are different in three different runs, so I do not think they are connected

**Comment by michalvavrik** [comment]
> Failures in Openshift are different in three different runs, so I do not think they are connected

I saw these failures 2 runs back, then it was replaced with that Infinispan counter failure. Considering that native is fine I think it is flaky.

**Comment by fedinskiy** [comment]
@michalvavrik could you remove the tag from the backported PRs?

**Comment by michalvavrik** [comment]
> @michalvavrik could you remove the tag from the backported PRs?

thanks, done

**Pull request merged**
