### PR TITLE
Revert "Disable reactive tests in `cache/caffeine`"

### PR DESCRIPTION
**Pull request by rsvoboda**
Revert "Disable reactive tests in `cache/caffeine`"

This reverts commit 50d90aad7867dbe05d5bbf2ed698a0b3155d869b.
https://github.com/quarkusio/quarkus/pull/22271 got merged

### CODE REVIEW

**Comment by rsvoboda** [comment]
Blocked by https://github.com/quarkusio/quarkus/issues/22431

**Comment by rsvoboda** [comment]
Returning `Uni<Void>` is the way for RESTEasy Reactive, see the description of fix for quarkusio/quarkus#22431.

**Comment by rsvoboda** [comment]
run tests

**Review by jsmrcka — APPROVED** [review]
Looks good.The use of `Uni<Void>` is currently undocumented, but I suppose the docs will be updated as mentioned here: https://github.com/quarkusio/quarkus/pull/22683#issue-1095153400.

**Comment by jsmrcka** [comment]
run tests

**Pull request merged**
