### PR TITLE
Reactive REST client, part2

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary
Follow-up on https://github.com/quarkus-qe/quarkus-test-suite/pull/580, adds coverage for sub-resources and proxies as well as some refactoring in a separate commit.
Test plan: https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-1415.md

Please select the relevant options.
- [x] New scenario (non-breaking change which adds functionality)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
@fedinskiy pls rebase

**Comment by rsvoboda** [comment]
Failure on Windows, pls investigate

Is Draft relevant?

**Comment by fedinskiy** [comment]
Draft is relevant, since proxy part is not yet ready.

Windows failure is due to known bug: https://github.com/quarkusio/quarkus/issues/24763, will disable this test later

**Comment by rsvoboda** [comment]
Linked issue say it's not a Quarkus bug, but error is in the test framework.

**Review by pjgg — APPROVED** [review]
Very good job!. LGTM

**Pull request merged**
