### PR TITLE
Upgrade AMQ Kafka Streams to 2.3.0

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

fixes: #1143

Previous AMQ Kafka Streams link is not valid anymore.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
OC JVM failure in `spring-web-reactive` module is not related as there is no AMQ, it only got triggered as there was a change in POM file

**Comment by michalvavrik** [comment]
Spring Web failure is also present in dailys, therefore I believe it is not related.

**Comment by michalvavrik** [comment]
run tests

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
