### PR TITLE
Enable tests with fixed issues

### PR DESCRIPTION
**Pull request by jedla97**
### Summary

Enable some tests. Some workaround added code so now it's removed as it's no longer needed.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]
LGTM, thx

**Pull request merged**
