### PR TITLE
Add Data Grid Serialization and cache eviction test

### PR DESCRIPTION
**Pull request by kshpak**
TD https://github.com/quarkus-qe/quarkus-test-plans/blob/main/QUARKUS-803.md
Finally, cache.clear() was used and it behaves stable on OpenShift.

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

**Comment by kshpak** [comment]
run tests

**Review by Sgitario — CHANGES_REQUESTED** [review]
Please, take a look into the OCP failures.

**Comment by kshpak** [comment]
Tests are relying on resources in target folder that were changed at runtime and needed to be re-set with defaults for the next test. As a solution, I decompose adjumstYml method

**Comment by Sgitario** [comment]
run tests

**Review by Sgitario — APPROVED** [review]

**Comment by kshpak** [comment]
@mjurc can you please take a look at this one

**Review by mjurc — APPROVED** [review]
Thanks for the PR!

**Comment by Sgitario** [comment]
@kshpak please backport to 2.2

**Comment by rsvoboda** [comment]
And update state of https://issues.redhat.com/browse/QUARKUS-803 to at leas Implemented, meybe go directly to Resolved.
Verified once we have full TS execution on Jenkins.

**Pull request merged**
