### PR TITLE
Cover custom init containers

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

https://issues.redhat.com/browse/QQE-507

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [x] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
Failure for "Hibernate FullText Search" is not related

run tests

**Comment by fedinskiy** [comment]
run tests

**Review by mjurc — COMMENTED** [review]
LGTM. I don't think the failures that appeared yet are related, but let's wait for the rest of the CI

**Comment by fedinskiy** [comment]
Failures in CI are related to Hibernate Full Text search module and can be seen in the daily build[1] as well (ergo, unrelated).


[1] https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/8352512463/job/22863308965

**Pull request merged**
