### PR TITLE
Backports/3.8 16.02

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

- https://github.com/quarkus-qe/quarkus-test-suite/pull/1650
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1651
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1653
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1637
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1645
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1659
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1664
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1667
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1671

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
https://github.com/quarkus-qe/quarkus-test-suite/pull/1667 was added

run tests

**Comment by michalvavrik** [comment]
Please check OCP failures.

**Comment by fedinskiy** [comment]
run tests

**Comment by michalvavrik** [comment]
Looks like there is no choice, the 3.8 branch requires squashing this :/

**Pull request merged**
