### PR TITLE
Bump test framework to 1.4.2.Beta8

### PR DESCRIPTION
**Pull request by mocenas**
### Summary

Bump test framework to 1.4.2.Beta8. Include recent changes

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by fedinskiy — CHANGES_REQUESTED** [review]
1. Please rebase
2. Should it be backported to 3.8?

**Comment by mocenas** [comment]
> 1. Please rebase
> 
>     2. Should it be backported to 3.8?

Rebased.
Yes this should be backported.

**Review by fedinskiy — CHANGES_REQUESTED** [review]
@mocenas there are still conflicts (I would say, due to usage of [merge](https://github.com/quarkus-qe/quarkus-test-suite/pull/1659/commits/ce9ff6eea67f7e3b0e272ce280429c8abb3525b4)). May be it would easier to create a new branch from main and force-push  it here

**Comment by mocenas** [comment]
> @mocenas there are still conflicts (I would say, due to usage of [merge](https://github.com/quarkus-qe/quarkus-test-suite/pull/1659/commits/ce9ff6eea67f7e3b0e272ce280429c8abb3525b4)). May be it would easier to create a new branch from main and force-push it here

You're right I accidentally merged something. I force-pushed it again from scratch. Now it should be OK.

**Review by fedinskiy — APPROVED** [review]

**Pull request merged**
