### PR TITLE
Properly disable the build of podman on openshift

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

Follow-up to https://github.com/quarkus-qe/quarkus-test-suite/pull/1981 which id double verified on our Jenkins

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
> Properly disable the build of podman on openshift 

I love that we did pre-flight PR. Let's pretend it was intentional, otherwise I'll look like lousy reviewer.

**Comment by fedinskiy** [comment]
> I love that we did pre-flight PR.

Well, we ran OC tests, but they didn't catch this

**Comment by fedinskiy** [comment]
weekly run on JVM and stable Openshift processed this module without any issues, so this can be merged

**Review by michalvavrik — APPROVED** [review]
IMO changes are correct.

**Pull request merged**
