### PR TITLE
Fix daily build by disabling Pact tests due to upstream issue, disabling Microprofile OpenTracing module that does work after deps renaming and rename extensions

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Fixes daily build and PRs CI by:

- disabling Pact due to upstream changes https://github.com/quarkiverse/quarkus-pact/issues/191
- https://github.com/quarkiverse/quarkus-smallrye-opentracing/blob/main/deployment/pom.xml#L22 contains reference to the `quarkus-resteasy-reactive-spi-deployment` relocations doesn't seem to fix this, possibly because the  OpenTracing wasn't build with new relocations?
```
2024-03-12T20:09:18.7394676Z [WARNING] The POM for io.quarkus:quarkus-resteasy-reactive-spi-deployment:jar:999-SNAPSHOT is missing, no dependency information available
```

Reflect changes in Quarkus reactive extension names as had already been done in the https://github.com/quarkus-qe/beefy-scenarios/pull/464:

- migrating to new Quarkus extension names https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#resteasy-reactive-extensions-renamed-to-quarkus-rest

Our own modules are not renamed as that would make backports hard and first and foremost, we need daily build green.

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
CR1 release happened yesterday -https://github.com/quarkus-release/release/issues/50

Full platform release is in 2 weeks. That's when registry, CLI version, etc. get updated.
I would disable the test for now and keep the changes. wdyt @mjurc

**Comment by mjurc** [comment]
@rsvoboda I don't really have a strong opinion either way

**Comment by michalvavrik** [comment]
Alright, disable it is.

**Comment by michalvavrik** [comment]
Awaiting approvals.

**Review by mjurc — APPROVED** [review]
LGTM

**Pull request merged**
