### PR TITLE
Update distributionUrl maven to 3.9.9

### PR DESCRIPTION
**Pull request by jcarranzan**
### Summary

This task is related to the maven upgrade to 3.9.9 and I've used the command to do the changes:
`mvn wrapper:wrapper -Dmaven=3.9.9`

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
Latest 3.9.z is 3.9.9, why moving to 3.9.6?

Please run `mvn wrapper:wrapper -Dmaven=3.9.9`.

There are other changes, e.g. in scripts.

**Comment by jcarranzan** [comment]
> Latest 3.9.z is 3.9.9, why moving to 3.9.6?
> 
> Please run `mvn wrapper:wrapper -Dmaven=3.9.9`.
> 
> There are other changes, e.g. in scripts.

I noticed that the latest stable version in the 3.9.x series is actually 3.9.9. Initially, I selected 3.9.6 based on previous discussions indicating that 3.9.6  was acceptable. 
 I’ll proceed with upgrading to 3.9.9 (run `mvn wrapper:wrapper -Dmaven=3.9.9`) and also update the other MRs I already did related to this in our infrastructure.
 Thanks.

**Review by michalvavrik — CHANGES_REQUESTED** [review]
There is no reason for tests to be failing, both daily build and my PR that run full CI are green, either you need to rebase this PR on current main or the failures are related. Please have a look.

**Review by michalvavrik — APPROVED** [review]
Cool, thanks. Many of our Jenkins jobs are using this wrapper, you should probably run them when this gets merged to have a smoke check.

**Comment by jedla97** [comment]
Just a note: For GH side 10th of January the maven 3.9.9 should be default on all runners. Source https://github.com/actions/runner-images/issues/11093

**Pull request merged**
