### PR TITLE
[3.2] Backport Quarkus CLI Windows fixes and Elasticsearch Rest Client test development

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Backports:

- https://github.com/quarkus-qe/quarkus-test-suite/pull/1410
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1409
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1407
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1401

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Review by fedinskiy — APPROVED** [review]
But lets wait for CI to finish

**Comment by michalvavrik** [comment]
Number of OCP failures is horrible, but they are in tests that this PR doesn't touch, therefore it shouldn't stop us.

**Comment by fedinskiy** [comment]
I did a clean-up, hopefully this will help

**Comment by michalvavrik** [comment]
Thanks, let's see.

**Comment by michalvavrik** [comment]
Just one failure in OCP JVM mode now and 2 in native OCP, I think these are chronically flaky.

**Pull request merged**
