### PR TITLE
[3.15] 3.15 backports 27.11.2024

### PR DESCRIPTION
**Pull request by jedla97**
### Summary
 
Backport contains:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2173
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2186
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2195
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2205
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2207
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2211
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2204
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2219
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2220
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2227

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
OCP failiures are related, looking at that

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
Run tests

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
run tests

**Comment by jedla97** [comment]
Removed https://github.com/quarkus-qe/quarkus-test-suite/pull/2215 as it was found that there is problem on openshift. This issue was standalone so it's not needed to verify 3.15.2

Won't run ocp again but will wait for result before push and comment here

**Comment by jcarranzan** [comment]
LGTM, let's wait for the cheks.

**Comment by jedla97** [comment]
OCP is green except failing `testHttp10WithoutHostHeader` which was removed as stated in previous comment. So Waiting on GH CI

**Comment by jedla97** [comment]
CI is green so merging

**Pull request merged**
