### PR TITLE
[3.15] Backports for 25.9

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary
Backports:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1960
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1994
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2007
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2021
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2019
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2023
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2026
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2029
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2003
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2032
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2036
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2042
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2037
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2039
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2041
- https://github.com/quarkus-qe/quarkus-test-suite/pull/2044

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by michalvavrik — COMMENTED** [review]
@fedinskiy I must admit I personally don't care much about it, but there is some directive from @rsvoboda that our team seems to follow that when you cherry-pick things, you keep "cherrypicked from ... " with `git cherry-pick -x sha`. Your commits don't seem to have it. What shall we do about it?

It kinda depends on how much of a work is it for you, I'd definitely not spend hour on fixing it, so just let me know.

**Comment by fedinskiy** [comment]
@michalvavrik I was not aware of this directive, is it written down somewhere?

It will take roughly ten minutes with my script, so that is not a problem

**Comment by michalvavrik** [comment]
> @michalvavrik I was not aware of this directive, is it written down somewhere?

I heard that suggestion many times from Rostislav in my PRs or where I reviewed it. After that, reviewers of my backports started to request it. No, I don't think it's written, but IMO it is followed now.

> It will take roughly ten minutes with my script, so that is not a problem

cool, if you don't ind please do it, and maybe share the script because I always do it manually :-)

**Comment by fedinskiy** [comment]
Done, will share my script in the chat

**Review by michalvavrik — APPROVED** [review]
LGTM

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
Natice OCP failure:
```
10:27:51,849 INFO  oc: 3m27s       Warning   Failed              pod/app-8d4596bd5-jmjvs    Failed to pull image "image-registry.openshift-image-registry.svc:5000/ts-qvmpwvozgi/app@sha256:dd515ef65a5fd75ff52518635826050000b8c1cb7d1285c02a7afb43d408d3a8": reading manifest sha256:dd515ef65a5fd75ff52518635826050000b8c1cb7d1285c02a7afb43d408d3a8 in image-registry.openshift-image-registry.svc:5000/ts-qvmpwvozgi/app: authentication required
```

I do not think it is related, but will rerun just in case

**Pull request merged**
