### PR TITLE
Add Oracle DB scenario

### PR DESCRIPTION
**Pull request by jsmrcka**
Part of test development for QUARKUS-1164.

### CODE REVIEW

**Review by Sgitario — CHANGES_REQUESTED** [review]
The workaround you did to disable Native build is not working (see CI failures).
In the Maven profile: add the property quarkus.package.type=fast-jar and it will work, and disable the tests.

**Comment by Sgitario** [comment]
run tests

**Comment by jsmrcka** [comment]
run tests

**Comment by Sgitario** [comment]
JVM failures:
- OpenShift Keycloak scenarios: Login page title should display application realm ==> expected: <Sign in to test-realm> but was: <Log in to test-realm> Reported in https://github.com/quarkus-qe/quarkus-test-suite/issues/259
- Serverless scenarios will be fixed in next Upstream version
- MariaDB103DatabaseIT and Postgresql12DatabaseIT failures are caused by RH registry is not configured in Jenkins nodes (cc @mjurc )
- OpenShiftMssqlDatabaseIT is fixed in https://github.com/quarkus-qe/quarkus-test-suite/pull/249

There were more issues that I need to investigate.

**Comment by Sgitario** [comment]
@jsmrcka please rebase this PR to 2.2

**Pull request merged**
