### PR TITLE
Remove `quarkus.container-image.build=false` from GH CI

### PR DESCRIPTION
**Pull request by pjgg**
### Summary

This PR introduces some amendments based on these comments: https://github.com/quarkus-qe/quarkus-test-suite/pull/438

  - Enable `DockerBuildIT` on native mode
  - Rename scenario to something more meaningful
  - Remove `quarkus.container-image.build=false` from GH CI

Please select the relevant options.
- [X] Refactoring

### Checklist:
- [X] Methods and classes used in PR scenarios are meaningful
- [X] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by rsvoboda — CHANGES_REQUESTED** [review]
Drop all occurrences of `-Dquarkus.container-image.build=false` from GH actions definition and put the property into windows profile - https://github.com/quarkus-qe/quarkus-test-suite/blob/main/docker-build/pom.xml#L24

**Comment by pjgg** [comment]
> Drop all occurrences of `-Dquarkus.container-image.build=false` from GH actions definition and put the property into windows profile - https://github.com/quarkus-qe/quarkus-test-suite/blob/main/docker-build/pom.xml#L24

By adding the following configuration to `maven-failsafe-plugin` is still not working:
```
  <systemPropertyVariables>
          <quarkus.container-image.build>false</quarkus.container-image.build>
 </systemPropertyVariables>
```

I am going to add `-Dquarkus.container-image.build=false` to windows CI job

**Review by rsvoboda — CHANGES_REQUESTED** [review]
```diff
diff --git a/docker-build/pom.xml b/docker-build/pom.xml
index d7a7bbb..1a427cb 100644
--- a/docker-build/pom.xml
+++ b/docker-build/pom.xml
@@ -10,6 +10,9 @@
     <artifactId>docker-build</artifactId>
     <packaging>jar</packaging>
     <name>Quarkus QE TS: Docker-build</name>
+    <properties>
+        <quarkus.container-image.build>true</quarkus.container-image.build>
+    </properties>
     <dependencies>
         <dependency>
             <groupId>io.quarkus</groupId>
@@ -29,6 +32,9 @@
                     <family>windows</family>
                 </os>
             </activation>
+            <properties>
+                <quarkus.container-image.build>false</quarkus.container-image.build>
+            </properties>
             <build>
                 <plugins>
                     <plugin>
diff --git a/docker-build/src/main/resources/application.properties b/docker-build/src/main/resources/application.properties
index b0122a8..3b210ec 100644
--- a/docker-build/src/main/resources/application.properties
+++ b/docker-build/src/main/resources/application.properties
@@ -1,4 +1,3 @@
-quarkus.container-image.build=true
 quarkus.container-image.group=qe
 # DON'T remove the spaces that are at the end of quarkus app name
 quarkus.application.name=hello-world-app
```

**Comment by pjgg** [comment]
> ```diff
> diff --git a/docker-build/pom.xml b/docker-build/pom.xml
> index d7a7bbb..1a427cb 100644
> --- a/docker-build/pom.xml
> +++ b/docker-build/pom.xml
> @@ -10,6 +10,9 @@
>      <artifactId>docker-build</artifactId>
>      <packaging>jar</packaging>
>      <name>Quarkus QE TS: Docker-build</name>
> +    <properties>
> +        <quarkus.container-image.build>true</quarkus.container-image.build>
> +    </properties>
>      <dependencies>
>          <dependency>
>              <groupId>io.quarkus</groupId>
> @@ -29,6 +32,9 @@
>                      <family>windows</family>
>                  </os>
>              </activation>
> +            <properties>
> +                <quarkus.container-image.build>false</quarkus.container-image.build>
> +            </properties>
>              <build>
>                  <plugins>
>                      <plugin>
> diff --git a/docker-build/src/main/resources/application.properties b/docker-build/src/main/resources/application.properties
> index b0122a8..3b210ec 100644
> --- a/docker-build/src/main/resources/application.properties
> +++ b/docker-build/src/main/resources/application.properties
> @@ -1,4 +1,3 @@
> -quarkus.container-image.build=true
>  quarkus.container-image.group=qe
>  # DON'T remove the spaces that are at the end of quarkus app name
>  quarkus.application.name=hello-world-app
> ```

and also do you want to remove `-Dquarkus.container-image.build=false` from `PR - Windows - JVM build - Latest Version` ?

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
