### PR TITLE
Migrate 006-quartz-manually and 017-quartz-cluster from the Beefy TS

### PR DESCRIPTION
**Pull request by Sgitario**
I migrated both modules into the scheduling/quartz.
In the future, we might have other scheduling tools other than quartz.

Fix https://github.com/quarkus-qe/quarkus-test-suite/issues/79

### CODE REVIEW

**Comment by Sgitario** [comment]
I could not run the scenarios onto OCP because our OCP instance is really unstable, but will do it before this PR got merged to double check these scenarios work fine.

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
run tests

**Comment by Sgitario** [comment]
@jsmrcka this is ready to be reviewed.

**Review by jsmrcka — APPROVED** [review]
LGTM

**Pull request merged**
