### PR TITLE
Add git rebase to PR CI and fix not running full CI when pom.xml is changed

### PR DESCRIPTION
**Pull request by jedla97**
### Summary

This adding the rebase for us to test on latest version of branch, it help only detect the changed file in the PR. Also the rebase fail if the contributor have outdated branch in this case 16 or more commits (in my POV it should be enough)

To test the rebase I used the f66d24d805480689a62b4f863bb3c64ca23ae3e8 commit as base for this branch

This PR also fix the problem when main `pom.xml` was updated but the PR also contains other changes (updating tests etc.) so only selected modules were run. Wth this fix all the modules will be executed.

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by jedla97** [comment]
@michalvavrik this should adress both issues which we hit this week. 

The fix for the pom should be definitely fixed

The second fix with running more modules I'll decision up to you as I think it's not "must have" thing. So if you don't agree with the solution I'll remove the commit.

**Comment by michalvavrik** [comment]
Thanks, I'll probably look in the evening or early tomorrow, I am bit engaged ATM.

**Comment by michalvavrik** [comment]
I am going to remove the `triage/flaky-test` label because the `PR - Linux - JVM build - Latest Version` workflow has started before https://github.com/quarkus-qe/quarkus-test-suite/pull/2211 was merged and I don't want to get confused when I analyze new flaky results.

**Review by michalvavrik — APPROVED** [review]
LGTM, thanks!

**Comment by michalvavrik** [comment]
> This PR also fix the problem when main pom.xml was updated but the PR also contains other changes (updating tests etc.) so only selected modules were run. Wth this fix all the modules will be executed.

No, I think it is fine. It could be improved, like if you change `.github/*` file and something in specific module there will still be an issue, but we don't need perfect, this is much more frequent situation; thx

**Pull request merged**
