### PR TITLE
Update Red Panda, Strimzi Kafka and Apicurio registry image version

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Updates Red Panda, Strimzi Kafka and Apicurio registry docker images. There is opened follow-up MR in Jenkins job project.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
Failure related, I'll look into it.

**Comment by michalvavrik** [comment]
run testsw

**Comment by michalvavrik** [comment]
run tests

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
