### PR TITLE
Backport/3.2

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

Backports: 
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1393
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1394
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1392
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1398
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1400

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by fedinskiy** [comment]
run tests

**Comment by michalvavrik** [comment]
@fedinskiy CLI failure is certainly down to something I have done with removing streams (just guessing though), but I don't have time today. If you won't manage to have a look, I'll debug it tomorrow and fix my mistake.

**Comment by michalvavrik** [comment]
although I don't see such change in backports, so I probably confused it with different stuff. Okay.

**Comment by fedinskiy** [comment]
@michalvavrik this is due to this change[1] (I can not find the PR for it, though). Will fix it asap


[1] https://github.com/quarkus-qe/quarkus-test-suite/commit/cc55ea28e29b1a5a6c29824dfac2bfe04637c354

**Comment by fedinskiy** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]
Nice!

I think native OCP failures are flaky, hence I'll merge it.

**Pull request merged**
