### PR TITLE
Draft: Enable back Qute test

### PR DESCRIPTION
**Pull request by fedinskiy**

### CODE REVIEW

**Comment by rsvoboda** [comment]
@fedinskiy did you review the failures, what's the plan with this PR?

**Comment by fedinskiy** [comment]
@rsvoboda it is due to https://issues.redhat.com/browse/QUARKUS-1695, looks like this was fixed in 2.7.2, will recheck in near future

**Comment by michalvavrik** [comment]
run test

**Comment by rsvoboda** [comment]
No longer relevant, test is already enabled and refactored

https://github.com/quarkus-qe/quarkus-test-suite/blob/main/qute/multimodule/qute-test/src/test/java/io/quarkus/ts/qute/test/LocalizedMessagesIT.java

**Pull request closed without merging**
