### PR TITLE
[3.2] Bump Quarkus to 3.2.8.Final

### PR DESCRIPTION
**Pull request by rsvoboda**
### Summary

Bump Quarkus to 3.2.8.Final

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by rsvoboda** [comment]
Didn't trigger OCP tests because I'm not sure if they are not designed just for the main branch.

**Comment by rsvoboda** [comment]
Adjusted .github/workflows/ci.yml to use 3.2.8.Final based CLI

**Review by fedinskiy — DISMISSED** [review]
But CI is a problem. I looks like we need to create an upstream issue and, probably, disable the test in question

**Comment by rsvoboda** [comment]
Disabled ServerSentEventsTraceOpentracingIT in monitoring/opentracing-reactive-grpc
Hitting RESTEasy Classic limits with SSE, details https://github.com/quarkusio/quarkus/issues/36979

**Review by fedinskiy — APPROVED** [review]

**Pull request merged**
