### PR TITLE
[3.8] Backports for 3.8.5+Update to 3.8.5

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary
Backports:
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1813
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1802 (only max parameters part)
- https://github.com/quarkus-qe/quarkus-test-suite/pull/1818

Also updates Quarkus version to 3.8.5 in POM and CI

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
@fedinskiy GzipMaxInputIT is failing in native in dailys and in PRs and QuarkusCliPomIntegrityIT is not persisting changes. Please include fixes before we proceed with this PR.

**Comment by michalvavrik** [comment]
`GzipMaxInputIT` is upstream bug in main branch and in 3.8. let's disable it for now.

**Comment by fedinskiy** [comment]
Removed GZIP and POM tests (they will be handled later by @jcarranzan).

**Review by michalvavrik — APPROVED** [review]
LGTM

**Pull request merged**
