### PR TITLE
[2.13] Bump quarkus.qe.framework.version from 1.2.0.Beta13 to 1.2.0.Final

### PR DESCRIPTION
**Pull request by jsmrcka**
### Summary

Motivation:
- https://github.com/quarkus-qe/quarkus-test-framework/pull/625 - merged in FW `1.2.0.Beta16`, fixes interop OCP failures.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by fedinskiy — APPROVED** [review]

**Comment by fedinskiy** [comment]
Restarted the tests with Quarkus 2.13

**Comment by jsmrcka** [comment]
I executed the OCP tests manually (custom jobs):
- JVM: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ci-distributed-ts-jvm-ocp-4/1/testReport/ - 1 failure in `infinispan-client`
- Native: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ci-distributed-ts-native-ocp-4/2/testReport/ - 1 failure in `knative-events`

I cannot reproduce both failures from local machine for either `2.13` branch (target), or `jsmrcka:bump-test-framework-2.13` (source).

**Comment by jsmrcka** [comment]
For comparison, here are baseline OCP test runs for `2.13` current head:
- JVM: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ci-distributed-ts-jvm-ocp-4/3/ - all green.
- Native: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ci-distributed-ts-native-ocp-4/4/ - all green.

There have been 3 failures observed with the TF `1.2.0.Final` (comapred to `1.2.0.Beta13`):
- JVM: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ci-distributed-ts-jvm-ocp-4/1/testReport/ - 1 failure in `infinispan-client`.
- Native: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ci-distributed-ts-native-ocp-4/2/testReport/ - 1 failure in `knative-events`.
- Native: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/jsmrcka-quarkus-main-rhel8-jdk17-openshift-ci-distributed-ts-native-ocp-4/jdk=openjdk-17,label=RHEL8%20&&%20xlarge,scenario=service-binding-modules/3/testReport/ - 1 failure in `postgresql-crunchy-reactive`.

The JVM failure (`infinispan-client`, part of `root-modules`) is likely to appear in INTEROP testing, but I would prefer to merge this PR and attend to the failures in a separate effort: https://trello.com/c/1wgFHvd4/1866-qe-ts-213-failures-after-bump-to-framework-120final.

WDYT @fedinskiy

**Comment by rsvoboda** [comment]
We have 2 topics to handle:

 - fix interop
 - findout what's broken in Beta14/15/16/Final

Please prepare `1.2.0.Beta13.1` ASAP with fix for interop and get it processed.

Findout what's broken in Beta14/15/16/Final right after interop case is fixed.

**Comment by fedinskiy** [comment]
I checked the changes, and was not able to reproduce the most concerning `inifnispan-client` failure either. Therefore, I am merging the changes "as is", with intention to investigate the failures later.

**Pull request merged**
