### PR TITLE
Bump the version of the framework

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

Update the framework to the new version[1]. This is required to solve bugs in interop tests and to fix several failures in OCP

[1] https://github.com/quarkus-qe/quarkus-test-framework/releases/tag/1.3.0.Beta1

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
Openshift tests seems to be failing due to some problem with pulling images and I can not reproduce it on a local machine. Therefore, I presume it it safe to merge

**Comment by fedinskiy** [comment]
run tests

**Review by rsvoboda — CHANGES_REQUESTED** [review]
Please use .Final version

**Comment by fedinskiy** [comment]
run tests

**Review by michalvavrik — CHANGES_REQUESTED** [review]
Hey @fedinskiy , OC failures look too bad. Please investigate. Anyway, I suggest we close the PR and do a brand new FW release with proper version and fixes. For example without further investigation I can't tell if `OperatorOpenShiftAmqStreamsKafkaStreamIT` is not related to Kafka version https://github.com/quarkus-qe/quarkus-test-framework/pull/638

**Comment by michalvavrik** [comment]
> Hey @fedinskiy , OC failures look too bad. Please investigate. Anyway, I suggest we close the PR and do a brand new FW release with proper version and fixes. ~~For example without further investigation I can't tell if `OperatorOpenShiftAmqStreamsKafkaStreamIT` is not related to Kafka version [quarkus-qe/quarkus-test-framework#638](https://github.com/quarkus-qe/quarkus-test-framework/pull/638)~~

**Comment by mjurc** [comment]
run tests

**Comment by fedinskiy** [comment]
@mjurc there is no reason to run tests on this PR at the moment, since execution is blocked by https://github.com/quarkus-qe/quarkus-test-framework/pull/638 and https://github.com/quarkus-qe/quarkus-test-framework/pull/633

**Comment by jsmrcka** [comment]
@fedinskiy FW `1.3.0.Beta1` is out, which contains among others:
- https://github.com/quarkus-qe/quarkus-test-framework/pull/633
- https://github.com/quarkus-qe/quarkus-test-framework/pull/638
- https://github.com/quarkus-qe/quarkus-test-framework/pull/625 - merged in `1.2.0.Beta16`, fixes interop OCP failures.

The latest FW release using Quarkus `2.13` is `1.2.0.Final`, which contains among others:
- https://github.com/quarkus-qe/quarkus-test-framework/pull/625 - merged in `1.2.0.Beta16`, fixes interop OCP failures.

I suggest to bump the FW used in TS:
- `main`: FW `1.3.0.Beta1` - in this PR.
- `2.13`: FW `1.2.0.Final` - in a separate PR: https://github.com/quarkus-qe/quarkus-test-suite/pull/975.

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
@jsmrcka these fixes were definitely not enough: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk17-openshift-ci-distributed-ts-jvm-ocp-4/45/#showFailuresLink

**Comment by michalvavrik** [comment]
I think the fixes never meant to address remaining failures.

**Comment by michalvavrik** [comment]
`OpenShiftLifecycleApplicationIT` should be disabled with reference to https://github.com/quarkusio/quarkus/issues/29451, I forgot to do that. Please disable it.

**Review by michalvavrik — DISMISSED** [review]
The PR is titled _Fix the error which affected 2.7 interop runs on OCP_ while 1.3.0.Beta1 is based on Quarkus 2.15.1 according to https://github.com/quarkus-qe/quarkus-test-framework/pull/639. I think that the PR won't fix 2.13 as you can't use this with 2.13 (dependency mess, similar to our issues with Kubernetes client). 

Could you kindly update PR title or description so I can understand what is expected outcome (e.g. if the title was Bump framework version I would know what to test...).

Thank you

**Review by rsvoboda — APPROVED** [review]

**Comment by rsvoboda** [comment]
CI is green, let's merge it.

**Pull request merged**
