### PR TITLE
Bump test framework to 1.3.0.Beta21

### PR DESCRIPTION
**Pull request by fedinskiy**
### Summary

(Summarize the problem solved by this PR, and how to verify it manually)

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by fedinskiy** [comment]
run tests

**Review by michalvavrik — COMMENTED** [review]
@fedinskiy I looked at OCP JVM failures, it looks related, can you have a look please?

**Comment by michalvavrik** [comment]
run tests

**Review by michalvavrik — CHANGES_REQUESTED** [review]
@fedinskiy please check OCP JVM, failures are related `java.lang.NoSuchMethodError: io.fabric8.openshift.client.NamespacedOpenShiftClient.load(Ljava/io/InputStream;)Lio/fabric8/kubernetes/client/dsl/ParameterNamespaceListVisitFromServerGetDeleteRecreateWaitApplicable;`

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
run tests

**Comment by fedinskiy** [comment]
run tests

**Review by michalvavrik — APPROVED** [review]
yeah, I agree. + this PR also solves remote dev mode failures in daily builds, so let's get it in

**Pull request merged**
