### PR TITLE
Update Quarkus QE test framework to 1.2.0.Beta15

### PR DESCRIPTION
**Pull request by mjurc**
* This update should address exceptions in cleanup for operator managed resources.

Depends on https://github.com/quarkus-qe/quarkus-test-framework/pull/609

### Summary

(Summarize the problem solved by this PR, and how to verify it manually)

Please select the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
Let's wait for https://github.com/quarkus-qe/quarkus-test-framework/pull/609, I'm here all week.

**Comment by mjurc** [comment]
run tests

**Comment by michalvavrik** [comment]
I didn't see failures of `HTTP: minimum` in last couple of daily builds, although none of changes in https://github.com/quarkus-qe/quarkus-test-framework/pull/609 shouldn't cause it. Can you double check before we merge it, please?

**Comment by michalvavrik** [comment]
OC tests didn't run as workers were offline.

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
I think following failures

_io.quarkus.ts.hibernate.reactive.openshift.OpenShiftHibernateReactiveMsSQLIT.io.quarkus.ts.hibernate.reactive.openshift.OpenShiftHibernateReactiveMsSQLIT
io.quarkus.ts.reactive.rest.data.panache.OpenShiftMssqlPanacheResourceIT.io.quarkus.ts.reactive.rest.data.panache.OpenShiftMssqlPanacheResourceIT
io.quarkus.ts.sqldb.sqlapp.OpenShiftMssqlDatabaseIT.io.quarkus.ts.sqldb.sqlapp.OpenShiftMssqlDatabaseIT_

are due to admin policy for mcr.microsoft.com/mssql/rhel/server:2019-latest that we dropped lately

**Comment by michalvavrik** [comment]
@fedinskiy failure `OpenShiftApiServerConfigMapConfigIT, OpenShiftApiServerConfigSecretConfigIT, OpenShiftConfigSourcePriorityIT, OpenShiftFileSystemConfigMapConfigIT, OpenShiftFileSystemConfigSecretConfigIT` are down to https://github.com/quarkus-qe/quarkus-test-suite/pull/886 
```bash
Failed to load config value of type class java.lang.String for: secret.ipFailed to load config value of type class java.lang.String for: the.answerFailed to load config value of type class java.lang.String for: secret.password
```
Could you please fix them and also check (make assumption) why it didn't appear in PR CI runs? I remember we run them. Thank you

@mjurc `OpenShiftLifecycleApplicationIT` is IMHO related to https://github.com/quarkus-qe/quarkus-test-suite/blob/main/lifecycle-application/pom.xml#L43, could you address the failure, please?

**Review by michalvavrik — CHANGES_REQUESTED** [review]
See my comment on `OpenShiftLifecycleApplicationIT`.

**Comment by mjurc** [comment]
> I think following failures
> 
> _io.quarkus.ts.hibernate.reactive.openshift.OpenShiftHibernateReactiveMsSQLIT.io.quarkus.ts.hibernate.reactive.openshift.OpenShiftHibernateReactiveMsSQLIT io.quarkus.ts.reactive.rest.data.panache.OpenShiftMssqlPanacheResourceIT.io.quarkus.ts.reactive.rest.data.panache.OpenShiftMssqlPanacheResourceIT io.quarkus.ts.sqldb.sqlapp.OpenShiftMssqlDatabaseIT.io.quarkus.ts.sqldb.sqlapp.OpenShiftMssqlDatabaseIT_
> 
> are due to admin policy for mcr.microsoft.com/mssql/rhel/server:2019-latest that we dropped lately

We should disable those tests as the workaround broken several operators. I've opened https://github.com/quarkus-qe/quarkus-test-suite/pull/891.

**Review by michalvavrik — APPROVED** [review]
I re-run from my workstation `OpenShiftLifecycleApplicationIT` with 1.2.0.Beta15 and it's fine.

**Comment by pjgg** [comment]
Do we need to backport this PR? @mjurc

**Pull request merged**
