### PR TITLE
Enable qpid module

### PR DESCRIPTION
**Pull request by gtroitsk**
### Summary

Activate qpid module as quarkus-qpid-jms 2.1.0 now uses Quarkus 3

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by gtroitsk** [comment]
run tests

**Comment by michalvavrik** [comment]
hey @gtroitsk OC JVM failure is not related, but please run `io.quarkus.qe.scheduling.spring.OpenShiftSpringScheduledIT` from your workstation and determine if that is flaky test or you can reproduce it, thx

**Comment by gtroitsk** [comment]
@michalvavrik I run `io.quarkus.qe.scheduling.spring.OpenShiftSpringScheduledIT` three times on my local machine and I have no errors.

**Comment by michalvavrik** [comment]
@gtroitsk perfect, thank you

**Review by michalvavrik — APPROVED** [review]
lgtm

**Pull request merged**
