### PR TITLE
Github CI: Run only changed modules in JVM for Linux and Windows

### PR DESCRIPTION
**Pull request by Sgitario**
Example of run when there is a change in a module: https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/1216700602

### CODE REVIEW

**Review by rsvoboda — APPROVED** [review]
Didn't spot anything suspicious, when root pom.xml (or anything in root directory) gets changed, full TS is executed.

Minor optimization: Would it be possible (in new PR) to avoid TS execution when only *.md files are changed?

**Comment by Sgitario** [comment]
JVM failure will be addressed in https://github.com/quarkus-qe/quarkus-test-suite/pull/251. Merging.

**Comment by Sgitario** [comment]
> Didn't spot anything suspicious, when root pom.xml (or anything in root directory) gets changed, full TS is executed.
> 
> Minor optimization: Would it be possible (in new PR) to avoid TS execution when only *.md files are changed?

I guess some optimizations can be done to be smarter +1

**Comment by Sgitario** [comment]
> Didn't spot anything suspicious, when root pom.xml (or anything in root directory) gets changed, full TS is executed.
> 
> Minor optimization: Would it be possible (in new PR) to avoid TS execution when only *.md files are changed?

I guess some optimizations can be done to be smarter +1

**Pull request merged**
