### PR TITLE
[DON'T MERGE - HERE TO TEST FLAKY COMMENTS ] Test flaky reporter comments

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

TSIA

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [ ] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by michalvavrik** [comment]
There is an issue with Java https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/11041992883/job/30673453268

**Comment by rsvoboda** [comment]
Following jobs contain at least one flaky test:
 * PR - Linux - JVM build - Latest Version
 * PR - Linux - Native build - Latest Version
 * PR - Windows - JVM build - Latest Version

Run summary: https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/11050962721?pr=2050

**Flaky tests:**

---
**`io.quarkus.ts.http.minimum.reactive.HttpMinimumReactiveIT.pathParamNameWithDash`**
 - Failure message: `failing to test flakiness reporting`
 - Failed in jobs:
   - ABC
   - EFG
<details>
<summary>Failure stacktrace</summary>

```
org.opentest4j.AssertionFailedError: failing to test flakiness reporting
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at io.quarkus.ts.http.minimum.reactive.HttpMinimumReactiveIT.pathParamNameWithDash(HttpMinimumReactiveIT.java:42)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```

</details>

---

**`io.quarkus.ts.http.minimum.reactive.HttpMinimumReactiveIT.pathParamNameWithDash`**
 - Failure message: `failing to test flakiness reporting`
 - Failed in jobs:
...

---

This ^^^ is how I would format the output @michalvavrik 
 * Jobs to be in list
 * Mentioned flaky-run-report.json is imho implementation detail and I didn't find such file in Artifacts section of https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/11050962721?pr=2050
 * stacktrace hidden by default, but expandable

Asks
 * Could you link the summary of the gh action run? 
 * How would report look in case of multiple tests flakiness - for example bound to a platform?
 * Can you provide details which jobs were affected by the flaky test?

**Comment by michalvavrik** [comment]
> This ^^^ is how I would format the output @michalvavrik

got it, but changes that I do in the TS/FW are independent on this. The Flaky Run reporter project is in charge of both creating reports and then creating content for the comments. So I'll have a look at the format and try to answer your questions / address it if possible. I just want you to know it won't be addressed here and it doesn't block changes I am making.

**Comment by michalvavrik** [comment]
> Could you link the summary of the gh action run?

> How would report look in case of multiple tests flakiness - for example bound to a platform?

if there is multiple flakes, each will be reported in the same fashion (it will be a list). so if you know exact name of the failed artifact, you can see there `flaky-run-report-linux-jvm-latest.json` which tells you it's the JVM with 999-SNAPSHOT latest and on Linux, right?

> Can you provide details which jobs were affected by the flaky test?

wait till this workflow finishes, it should be there as I rebased it on the https://github.com/quarkus-qe/quarkus-test-suite/pull/2054

Ad proposed format and link to the summary, I'll see what I can do, but I am afraid I'll know to pass information to the script or maybe these information are available as env vars etc. I'll check it out and see.

**Comment by michalvavrik** [comment]
@rsvoboda ^^^ I consider job done.

**Pull request closed without merging**
