### PR TITLE
Bump quarkus-test-framework to 1.2.5.Final

### PR DESCRIPTION
**Pull request by mjurc**
### Summary

* This is needed to make the Kafka Operator tests pass with new Kafka

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [ ] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [x] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Comment by mjurc** [comment]
run tests

**Comment by mjurc** [comment]
run tests

**Comment by mjurc** [comment]
@michalvavrik Ready for review now, the MR was based on wrong branch before :sweat_smile:

**Review by michalvavrik — APPROVED** [review]

**Comment by michalvavrik** [comment]
Thanks!

**Comment by michalvavrik** [comment]
bare-metal JVM timed out I guess, OCP jvm flaky.

**Pull request merged**
