### PR TITLE
Disable DEV mode continuous testing scenarios due to upstream re-working

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

Disabled DEV mode tests using continuous testing. Currently there is no button to enable continuous testing, new dedicated page is expected in next days, then we need to adapt FW, release it and enable tests here.

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency update
- [ ] Refactoring
- [x] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by rsvoboda — APPROVED** [review]

**Comment by michalvavrik** [comment]
hey @rsvoboda , sorry to push changes to already approved PR, but I didn't manage to adapt DEV UI tests in `http-advanced` and `http-advanced-reactive` modules either as DEV UI parts that for GRPC service won't load at all (in new DEV UI pages, and old ones are gone). I'll check with developer if 404 for scripts lookup that I can see when I load `/q/dev-ui/` is known bug, but I suggest we wait a little before trying to adapt for DEV UI that is very much in progress. I'll go back to this together with enabling continuous testing.

**Comment by michalvavrik** [comment]
http-advanced/-reactive are failing in dailys too

**Comment by michalvavrik** [comment]
image

**Comment by michalvavrik** [comment]
failures are quite interesting, I can't reproduce this locally (also not related...), I'll debut it though

**Comment by rsvoboda** [comment]
I've reset the approval, no worries @michalvavrik

**Comment by michalvavrik** [comment]
@rsvoboda CI looks good now

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
