### PR TITLE
Bump FW to 1.3.0.Beta16, manage HTMLUnit dependency and silent its logging

### PR DESCRIPTION
**Pull request by michalvavrik**
### Summary

https://github.com/quarkus-qe/quarkus-test-framework/pull/781 follow up. Bumps FW, manages HTMLUnit dependency itself and sets is logging to off level

Please select the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Dependency update
- [x] Refactoring
- [ ] Backport
- [ ] New scenario (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] This change requires execution against OCP (use `run tests` phrase in comment)

### Checklist:
- [ ] Methods and classes used in PR scenarios are meaningful
- [x] Commits are well encapsulated and follow [the best practices](https://cbea.ms/git-commit/)

### CODE REVIEW

**Review by jsmrcka — APPROVED** [review]
Looks good.

Merge once the FW release is out and the CI is clean.

**Comment by michalvavrik** [comment]
I'll rerun CI when 1.3.0.Beta16 is in Maven central, run OC tests and wait for green CI.

**Comment by michalvavrik** [comment]
run tests

**Comment by michalvavrik** [comment]
`io.quarkus.ts.http.graphql.OpenShiftGraphQLTracingIT.verifyTracesInJaegerTest` and `io.quarkus.ts.http.graphql.telemetry.OpenShiftGraphQLTelemetryIT.verifyTelemetry` failures IMO goes down to https://github.com/quarkusio/quarkus/issues/33412 
and `OperatorOpenShiftInfinispanCountersIT.testMultipleClientDataAfterRestartInfinispanCluster` is something we saw before. It's flaky, I investigated it few weeks ago. I need to come back to it.

**Comment by michalvavrik** [comment]
Native OCP `io.quarkus.ts.micrometer.prometheus.kafka.reactive.OpenShiftAmqStreamsAlertEventsReactiveIT.testAlertMonitorEventStream
io.quarkus.ts.micrometer.prometheus.kafka.reactive.OpenShiftKafkaAlertEventsReactiveIT.testAlertMonitorEventStream` also flaky, adding it on my list.

**Pull request merged**
